### DISCUSSION TITLE
Kanal LEVEL_COMBINED aufnehmen bei Jalousie-Aktoren?

### DISCUSSION THREAD

**Discussion by ZungeWegIchFurze** [SukramJ/aiohomematic#1000] [Ideas]
Hallo an die Entwickler,

ich nutze den Jalousie-Aktor HM-LC-Ja1PBU-FM. (es gibt von Homematic (IP) noch einige weitere Jalousie-Aktoren, wie z.B.  HmIP-BBL-2).

Diese Jalousie-Aktoren haben einen Datenpunkt **LEVEL_COMBINED** (siehe auch: https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM-Script_4-Datenpunkte.pdf). An diesen Datenpunkt kann ein String übergeben werden, der zwei Hexwerte enthält, z.B. "0x00,0x50"
Der erste Hexwert ("0x00" in dem Fall 0) steht dabei für die Position der Jalousie und der zweite Hexwert ("0x50" in dem Fall für 80) steht für die Position der Lamellen.

Die Position und Winkelstellung der Jalousie kann mit LEVEL_COMBINED also in einem Befehl übergeben werden. Das hat den Vorteil, dass der Aktor den Befehl sehr viel schneller ausführt, als wenn man in Home Assistant erst "set_position" und später mit einer Automation dann "set_tilt_position" ausführt.

Deshalb stelle ich die Frage an die Entwickler, ob die Implementierung des Datenpunkts LEVEL_COMBINED in Home Assistant geplant ist.

Unabhängig davon: vielen Dank für Eure Benmühungen bei diesem Projekt. :)

Viele Grüße
Christoph

**Comment by danielperna84** [comment]
Schau mal, ob du's mit dem Service [homematicip_local.set_device_value](https://github.com/danielperna84/custom_homematic#homematicip_localset_device_value) manuell hin bekommst. [Hier](https://github.com/danielperna84/hahomematic/discussions/955#discussioncomment-4949739) siehst du, wie der bei einem anderen Gerät benutzt wird.

**Reply by ZungeWegIchFurze** [reply]
Sieht sehr vielversprechend aus. Vielen Dank.

Nur eine Frage: homematic**ip**_local klingt nach Homematic IP. Mein Aktor ist ein Homematic Gerät. Funktioniert es trotzdem?

**Reply by danielperna84** [reply]
Ja, die Integration heißt halt so.

**Comment by ZungeWegIchFurze** [comment]
Es funktioniert. Vielen Dank!

Zum Testen habe ich einen Button in der UI angelegt. Der YAML Code lautet:
```

show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: homematicip_local.set_device_value
  target: {}
  data:
    device_id: b7a1a017a363b9dcd1d379c31607d348
    channel: 1
    parameter: LEVEL_COMBINED
    value_type: string
    value: 0x00,0x50

```

Hier ein paar Beispiele für Hexwerte und die dazugehörige Position:

Behanghöhe oder Lamellenstellung in % vs. Hex:

0%  --- 0x00
10% --- 0x14
20% --- 0x28
30% --- 0x3C
40% --- 0x50
50% --- 0x64
60% --- 0x78
70% --- 0x8C
80% --- 0xA0
90% --- 0xB4
100% --- 0xC8

**Reply by SukramJ** [reply]
Stimmen die Hex-Werte? Nach meiner Rechnung sind die Werte alle doppelt so hoch.

**Reply by ZungeWegIchFurze** [reply]
Ja, die Werte stimmen. Man muss den gewünschten Hex-Wert verdoppeln um den gewünschten Prozentwert zu bekommen. Selbst getestet.

**Reply by SukramJ** [reply]
Hast Du das nur ausprobiert, oder auch noch eine andere Quelle gefunden?

**Reply by ZungeWegIchFurze** [reply]
Dokumentiert ist das seitens Homematic nicht. Das Wissen über die Verdopplung der Hex-Werte habe ich aus Foren und kann das erfolgreich nachbilden. Setze ich den Hex Wert auf 0x50 (= dezimal 80) steht in der CCU die Lamelle auf 40%.

**Comment by ZungeWegIchFurze** [comment]
Nun wollte ich einen Schritt weitergehen und genau diese Konfiguration in eine Entitie-Card bringen und die Jalousien um einen Knopf erweitern via "extend_paper_buttons_row" (https://github.com/jcwillox/lovelace-paper-buttons-row)

```
type: entities
entities:
  - entity: cover.wohnzimmerjalterasse
    extend_paper_buttons_row:
      buttons:
        - tooltip: Sichtschutz
          icon: mdi:eye-off-outline
          tap_action:
            action: call-service
            service: homematicip_local.set_device_value
            target: {}
            data:
              device_id: b7a1a017a363b9dcd1d379c31607d348
              channel: 1
              parameter: LEVEL_COMBINED
              value_type: string
              value: 0x00,0x50
```

Nun erhalte ich den Fehler:

Failed to call service homematicip_local/set_device_value. required key not provided @ data['device_id']

Hast Du eine Idee? Derselbe Code läuft mit einer Button-Card ohne Probleme.

**Comment by jschroeter** [comment]
Beim HmIP-FBL Jalousieaktor besteht die gleiche Problematik: wenn man z.B. in einer Szene oder Automation die Behanghöhe und Lamellenposition gleichzeitig setzen will funktioniert es nicht.

Die Lösung ist für den HmIP-FBL ähnlich, allerdings heißt der Parameter `COMBINED_PARAMETER` und die Value ist Plain-Text (also nicht Hex) im Format `L2=<Lamellenposition>,L=<Behanghöhe>`, also z.B. `L2=50,L=50`. Siehe auch meinen Kommentar hier: https://github.com/rdmtc/node-red-contrib-ccu/issues/154#issuecomment-1079763871

Hier ein vollständiges Beispiel für einen Button der beides auf 50% setzt:

```
show_name: true
show_icon: true
entity: cover.schlafzimmer_1_jalousie
show_state: true
type: button
tap_action:
  action: call-service
  service: homematicip_local.set_device_value
  target: {}
  data:
    device_id: 9d42ea66c59927c05d86b53c0af24d82
    channel: 4
    value_type: string
    value: L2=50,L=50
    parameter: COMBINED_PARAMETER
```

Das funktioniert wunderbar. Aber es hat mich Tage und Nächte gekostet das herauszufinden zumal es seitens EQ-3 quasi kaum dokumentiert ist.

Wäre es möglich dies in hahomematic irgendwo abzufangen? D.h. kann man erkennen wenn der Nutzer (per Szene oder Automation) beide Werte setzen möchte und dann intern dies zu einem Call kombinieren und eben LEVEL_COMBINED bzw. COMBINED_PARAMETER setzen? Das wäre genial und würde sicher einige Nerven bei Besitzern dieser Aktoren ersparen.

**Reply by SukramJ** [reply]
> Wäre es möglich dies in hahomematic irgendwo abzufangen? 

Ich denke das macht keinen Sinn. 
Für Automatisierungen könnte man einen eigenen Service anbieten, der beide Parameter übergibt.

**Reply by SukramJ** [reply]
In der Beta `1.33.2b0` gibt es einen neuen Service `homematicip_local.set_cover_combined_position` bei dem man `position` und `tilt_position` setzen kann. Dieser Service sollte für HM und HmIP Jalousien funktionieren.

Ich bitte um Feedback. Bitte schreibt dazu mit welchem Aktor ihr getestet habt.

**Reply by ZungeWegIchFurze** [reply]
Vielen Dank für Deine Mühen. Feedback folgt von mir leider erst Ende der nächsten Woche, wenn ich wieder Zuhause bin.

**Reply by SukramJ** [reply]
~~Version [1.33.2b0](https://github.com/danielperna84/custom_homematic/releases/tag/1.33.2b0) funktioniert mit HA 2023.3.x.
Version [1.34.0b2](https://github.com/danielperna84/custom_homematic/releases/tag/1.34.0b2) benötigt mindestens HA 2023.4 Beta~~

**Reply by jschroeter** [reply]
Danke für deinen Einsatz! Kannst du mir einen Hinweis geben wie ich die Beta-Versionen installieren kann? Ich habs auf die Schnelle nicht heraus gefunden. Dann probiere ich es gerne aus.

**Reply by SukramJ** [reply]
Auf der Integrationsseite in HACS auf erneut herunterladen klicken, dann kann man auf _Beta-Versionen anzeigen_ klicken.

**Reply by jschroeter** [reply]
Danke! Ich habe 1.33.2b0 erfolgreich mit HmIP-FBL getestet, funktioniert wunderbar. Das ist definitiv eine deutliche Verbesserung, allerdings muss man es wissen - ich denke ich bin nicht der einzige der versucht hat eine HA Szene zu erstellen und dort eben beide Positionen zu definieren. Das funktioniert logischerweise nach wie vor nicht. Daher mein Gedanke ob man das nicht auch irgendwie abfangen kann.

**Reply by SukramJ** [reply]
Danke für die Rückmeldung.

Das mit dem _abfangen_ ist einfacher geschrieben als umgesetzt. 
Um nur mal ein Beispiel zu nennen: 
Für wie lange willst du denn die erste Aktion abgefangen und **nicht** auf dem Aktor angewendet haben, bevor man dann feststellt, das die Folgeaktion ausgeblieben ist, und man die erste Aktion dann doch alleine ausführen muss? 
Ich werde hier nicht versuchen irgendwelche API Defizite zu kompensieren, die meinen Supportaufwand erhöhen, zu mal ich selber keine Jalousien damit steuern will.

Das einzig richtige Vorgehen wäre, das HA die API für `cover` entsprechend erweitert, aber ich werde hierzu keinen Feature Request erstellen. 

Bis dahin: Pech gehabt bei Szenen.

**Reply by jschroeter** [reply]
Vermutlich würden 1ms oder so schon reichen als Wartezeit, dadurch sollte beim Setzen eines einzelnen Werts keine spürbare Verzögerung entstehen.
Aber ich bin bei dir, es wäre ein unschöner und ggf. auch risikoreicher Workaround. Die Ursache des Problems liegt eigentlich bei Homematic, ich meine warum ignoriert/vergisst der Aktor einen der Werte wenn man beide kurz hintereinander setzt?! Das sollte doch eigentlich nicht sein.

In wie fern könnte HA die `cover` API entsprechend erweitern?

Genau genommen geht es nicht nur um Szenen sondern auch um Automatisierungen bei denen man problemlos beide Werte setzen kann und sich dann wundert warum es nicht funktioniert. Wenn man in dem Fall wenigstens eine Hinweismeldung anzeigen könnte, dass man doch bitte den neuen Service dafür nutzen soll wäre auch schon viel gewonnen. Aber ich vermute das ist auch nicht einfach möglich?

**Reply by SukramJ** [reply]
> risikoreicher Workaround

Genau das ist der Punkt!

> In wie fern könnte HA die cover API entsprechend erweitern?

Es gibt nur die Services [set_cover_position](https://developers.home-assistant.io/docs/core/entity/cover#set-cover-position) und [set_cover_tilt_position](https://developers.home-assistant.io/docs/core/entity/cover#set-cover-tilt-position) aber keinen Service der beide Parameter unterstützt und in der restlichen UI unterstützt wird. 
In einer Integration werden die Services entsprechend der API implementiert, damit auch die Integration(!) mit der UI funktioniert. 
Integrationsspezifische Services wie homematicip_local.set_cover_combined_position kann man nur in Automatisierungen verwenden.

> Hinweismeldung anzeigen 

Ich gebe immer den Hinweis regelmäßig mal die Doku zu lesen.

**Reply by SukramJ** [reply]
@ZungeWegIchFurze Schon zum Testen gekommen?

**Reply by ZungeWegIchFurze** [reply]
> @ZungeWegIchFurze Schon zum Testen gekommen?

Bei mir wird die genannte Beta nicht angezeigt (Haken für Beta anzeigen ist gesetzt). Gibt es schon eine neuere Beta? 

Ich bin leider recht neu bei Home Assistant dabei. Sorry. Dauert etwas länger bei mir.

**Reply by SukramJ** [reply]
Hat sich erledigt. Die Beta war vor zwei Wochen aktuell. Mittlerweile gibt es Version 1.34.1.

**Reply by ZungeWegIchFurze** [reply]
Ich werde es testen und Feedback geben. Vielen Dank für Deine Bemühungen!

**Reply by ZungeWegIchFurze** [reply]
Es läuft hervorragend! Vielen Dank für die Umsetzung.

Beispiel für eine Button-Card:


```
tap_action:
  action: call-service
  service: homematicip_local.set_cover_combined_position
  target: {}
  data:
    device_id: b7a1a017a363b9dcd1d379c31607d348
    position: 50
    tilt_position: 50
```
