### DISCUSSION TITLE
Wie Channel und Parameter eines Geräts herausfinden?

### DISCUSSION THREAD

**Discussion by ZungeWegIchFurze** [SukramJ/aiohomematic#1085] [General]
Hallo zusammen,

ich möchte für den Dimmer HM-LC-Dim1T-CV die möglichen Channels und Parameter herausfinden. Gibt es ein Dokument, in dem diese Angaben zu finden sind?

```
        tap_action:
          action: call-service
          service: homematicip_local.set_device_value
          service_data:
            device_id: 7b92e448a93f
            channel: ???
            parameter: ???
            value: ???
```

Konkret möchte ich die Leuchte auf xx% dimmen.

Vielen Dank und viele Grüße
Christoph

**Comment by ZungeWegIchFurze** [comment]
Ich konnte es selbst lösen. Für alle anderen:

HM Produkte sind hier beschrieben: https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM-Script_4-Datenpunkte.pdf
HM IP Produkte sind hier beschrieben: https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf

Um also auf 20% zu dimmen, ist folgender Code zu gebrauchen:

```
        tap_action:    
          action: call-service
          service: homematicip_local.set_device_value
          service_data:
            device_id: 7b92e448a93f
            channel: 1
            parameter: LEVEL
            value: "0.2"
```

**Reply by emufan** [reply]
Ich hab den Dimmer nicht selbst. Aber hast Dud as gerät nicht als Gerät in HA mitsamt light oder was auch immer entität und kannst es nicht ganz normal in HA setzen ohne einen set_device_value zu nutzen?

**Reply by ZungeWegIchFurze** [reply]
Hallo emufan,

ich kann mit light.turn_on und brightness die Leuchte dimmen. Aber sobald ich diese Befehle zusammen mit dem Add-On https://github.com/jcwillox/lovelace-paper-buttons-row nutzen möchte, klappt folgende Syntax einfach nicht. Ich denke, dass es an paper buttons row liegt.

```
    tap_action:
      action: call-service
      service: light.turn_on
      data:
        brightness: 50
      target:
        device_id: 80e86e7f050138774151983778feecdc
```

Aus diesem Grund bin auf homematicip_local.set_device_value umgestiegen. Damit klappt es.
