### DISCUSSION TITLE
Programme in Dashboard anzeigen

### DISCUSSION THREAD

**Discussion by Schleek** [SukramJ/aiohomematic#1092] [General]
Hallo allerseits, 

Ich bin noch recht neu in Sachen Home Assistant. Ich habe meine CCU3 dank dieser Integration erfolgreich verbunden. Nun versuche ich meine auf der CCU3 definierten Programme im Dashboard anzuzeigen. Ich sehe die "Controls" und klicke auf « Add to dashboard". Das übernächste Fenster "We created a suggestion for you" bleibt jedoch leer. Wie kann ich meine Programmliste manuel im Dashboard hinzufügen?

**Comment by emufan** [comment]
Programme sind ja auch nur Entitäten im HA und die kannst Du nutzen, woimmer Du willst.

```
type: vertical-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    name: Text
    tap_action:
      action: toggle
    entity: button.homematic_p_ccu3_led
  - type: entities
    entities:
      - entity: button.homematic_p_ccu3_led
        name: text
```

![image](https://github.com/danielperna84/hahomematic/assets/22775515/f87261f2-6141-4a33-b91b-de674f4b2bd2)

**Reply by Schleek** [reply]
Danke emufan für die schnelle und hilfreiche Antwort. Ich habe das jetzt einmalm beispielhaft so eingebunden : 
```
type: vertical-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    name: Text
    tap_action:
      action: toggle
    entity: button.ccu3_webui_p_all_stores_up
  - type: entities
    entities:
      - entity: button.ccu3_webui_p_all_stores_up
        name: text
```
Leider wird die Entität nicht gefunden (This entity is unavailable.). Es handelt sich hierbei um ein Programm auf der CCU3, das dafür sorgt, dass alles Raffstores hochgezogen werden. Es ist auch als Favorit gespeichert. Woran kann das liegen ?

**Edit :** Ok musste die Entitäten aktivieren. Jetzt klappt es, danke !
