### DISCUSSION TITLE
Need help translating config of old itegration to new one

### DISCUSSION THREAD

**Discussion by gnampf89** [SukramJ/aiohomematic#1153] [Q&A] [answered]
I keep getting authentication errors despite using same and known to be working ip/user/password

```
homematic:
  interfaces:
    HmIP:
      host: ccu3-webui.fritz.box
      port: 2010
      resolvenames: json
      username: homeassistant
      password: !secret ccu3_password
  hosts:
    ccu3:
      host: ccu3-webui
      username: homeassistant
      password: !secret ccu3_password
```
so far I reverted to the old integration, but that does not support some newer devices, which was the reason I found this integration in the first place.
