### DISCUSSION TITLE
Support for Long press released

### DISCUSSION THREAD

**Discussion by eloo** [SukramJ/aiohomematic#1254] [Ideas]
Hi there,

i was just about to setup an automation using the blueprint for my RC with 8 Buttons and sadly discovered that currently only Long Press as event is supported.
But this leads to continued executions of my service behind (toggle a plug) and that a bit problematic for a common switch action.

So i would like to suggest to support the button long press released event so the action will only be executed once.

Here is an example of an event flow when "long press" is used

````
---
    data:
      address: 000B1BE99410CF
      device_type: HmIP-RC8
      interface_id: RaspberryMatic-HmIP-RF
      value: true
      device_id: a9cf3bd01c97f29e0c0920dfb9aec669
      name: HmIP-RC-1
      type: press_long
      subtype: 8
---
    data:
      address: 000B1BE99410CF
      device_type: HmIP-RC8
      interface_id: RaspberryMatic-HmIP-RF
      value: true
      device_id: a9cf3bd01c97f29e0c0920dfb9aec669
      name: HmIP-RC-1
      type: press_long_start
      subtype: 8
---
    data:
      address: 000B1BE99410CF
      device_type: HmIP-RC8
      interface_id: RaspberryMatic-HmIP-RF
      value: true
      device_id: a9cf3bd01c97f29e0c0920dfb9aec669
      name: HmIP-RC-1
      type: press_long
      subtype: 8
---
    data:
      address: 000B1BE99410CF
      device_type: HmIP-RC8
      interface_id: RaspberryMatic-HmIP-RF
      value: true
      device_id: a9cf3bd01c97f29e0c0920dfb9aec669
      name: HmIP-RC-1
      type: press_long_release
      subtype: 8
```

Its important here to mention that this event flow is valid for "Timeout für langen Tastendruck" = Deaktiviert
![image](https://github.com/danielperna84/hahomematic/assets/2631895/132afcea-ea91-4800-8b11-d00cbba6f4e5)

An example blueprint with button release can be found here: https://gist.github.com/freakshock88/cbc0909e874cf82118a843721d72f656

Thanks

**Comment by SukramJ** [comment]
Not sure what’s your problem.
All press events are already supported.
Did you add long press released to you [dummy program](https://github.com/danielperna84/custom_homematic#events-for-homematicip-devices)?

**Comment by eloo** [comment]
Ah okay, maybe its a bit unclear what i'm talking exactly about..

Its related to the blueprint provided by the custom component.

to be more precise the captured event by the blueprints like we see here:
https://github.com/danielperna84/custom_homematic/blob/devel/blueprints/automation/homematicip_local-actions-for-8-button.yaml#L177

Only 
`press_short`
and
`press_long`

is supported here

```
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.type  == 'press_short' and trigger.event.data.subtype  == 7 }}"
        sequence: !input "action_7_short"
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.type  == 'press_long' and trigger.event.data.subtype  == 7 }}"
        sequence: !input "action_7_long"
```

but not `press_long_release`
