### DISCUSSION TITLE
Unterstützung von HB-UNI-RGB-LED-CTRL

### DISCUSSION THREAD

**Discussion by patman15** [SukramJ/aiohomematic#1286] [Ideas]
Hallo!

PR habe ich gemacht https://github.com/danielperna84/pydevccu/pull/42 und ich würde das Gerät gerne als RGB Dimmer in HA verwenden. Wie kann ich das erreichen?

Danke!

**Comment by SukramJ** [comment]
Ich hab eigentlich nicht vor alle HB Geräte zu integrieren.
Da aber über die Integration zur Verfügung gestellt werden kannst Du selber über ein [Template](https://www.home-assistant.io/integrations/light.template/) einen RGB Dimmer erstellen.

**Reply by patman15** [reply]
> Ich hab eigentlich nicht vor alle HB Geräte zu integrieren.

Ok, habe ich mir fast gedacht, ist doch ein wenig aufwendig. Danke für den Hinweis mit dem Template.

Falls es mal nach mir noch wer braucht (hab ziemlich Zeit mit den Wertebereichen vertan, weil die Doku von HA da nicht sehr eindeutig ist), hier ist meine Vorlage:

```
light:
  - platform: template
    lights:
      cust_dim:
        friendly_name: CustomDimmer
        unique_id: mydim01
        level_template: "{{ (states('number.cust_dim_level') | float * 2.55) | int }}"
        value_template: "{{ states('number.cust_dim_level') | int > 0}}"
        color_template: "({{ states('number.cust_dim_color') | float / 199 * 360 }}, {{ 0 if (states('number.cust_dim_color') | int == 200) else 100 }})"
        availability_template: "{{ has_value('number.cust_dim_level') }}"
        effect_list_template: "{{ ['Aus','Langsamer Durchlauf', 'Normaler Durchlauf', 'Schneller Durchlauf', 'Lagerfeuer', 'Wasserfall', 'TV Simulation'] }}"
        effect_template: "{{ ['Aus','Langsamer Durchlauf', 'Normaler Durchlauf', 'Schneller Durchlauf', 'Lagerfeuer', 'Wasserfall', 'TV Simulation'][states('number.cust_dim_program')|int] }}"
        turn_on:
          service: homematicip_local.set_device_value
          data:
            channel: 1
            value_type: double
            value: 1
            parameter: LEVEL
            device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        turn_off:
          service: homematicip_local.set_device_value
          data:
            channel: 1
            value_type: double
            value: 0
            parameter: LEVEL
            device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        set_level:
          service: homematicip_local.set_device_value
          data:
            channel: 1
            value_type: double
            value: "{{ (brightness/255) }}"
            parameter: LEVEL
            device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            
        set_color:
          - service: homematicip_local.set_device_value
            data:
              channel: 2
              value_type: int
              value:  "{{ (h/360*199) | int if (s > 50) else 200 }}"
              parameter: COLOR
              device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        set_effect:
          service: homematicip_local.set_device_value
          data:
            channel: 3
            value_type: int
            value: "{{['Aus','Langsamer Durchlauf', 'Normaler Durchlauf', 'Schneller Durchlauf', 'Lagerfeuer', 'Wasserfall', 'TV Simulation'].index(effect) }}"
            parameter: PROGRAM
            device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       
```
