### DISCUSSION TITLE
Parallel Interfaces

### DISCUSSION THREAD

**Discussion by emufan** [SukramJ/aiohomematic#130] [Q&A] [answered]
Da ich nicht weiß, die die Event- und Status-Subscribierungen, usw. funktionieren, mal die Frage, wie sich parallel Instanzen und Interfaces beeinflussen oder beeinflussen könnten.

Ich habe ja meinen "Prod-HA" und dort nur die alte Integration. Hatte dort nur kurz die neue per HACS installiert, aber nie eingerichtet. Und dort auch schon wieder gelöscht.

Und dann habe ich meine Test-Instanz, wo auch die alte Integration läuft und parallel die neue von hier.

Vorher dachte ich, dass das alles separat funktioniert und die Integrationen ha keine eigenen IDs oder so in die CCU zurückschreiben. Aber dann habe ich mir überlegt, woher alle drei Integrationen überhaupt alles gemeldet bekommen. Das würde mich mal generell interessieren. Eilt aber nicht.

Ich habe aktuell aber ab und an das Problem, dass sich die BROLL-Status in der alten Integration verabschieden. Fiel mir erst auf zum parallelen BROLL-Problem in den Issues. Manchmal zeigt Prod-HA von jetzt auf gleich keine Positionen mehr an (Modifikation eingebaut), mal (seltener) die Test-Instanz. Nach Reboot geht es dann wieder. Ist aber suspekt. Und daher kam mir die Frage (auch wg. des aktuellen Climate-Error-Issues), ob das doch an den drei parallelen Zugriffen liegen kann?

**Comment by SukramJ** [comment, marked as answer]
Der Instanzname muss auf jeder HA Installation anders.
Zusammen mit dem Schnittstellennamen, der mittlerweile nicht mehr über den CF gepflegt werden muss, bildet sich die Interface-ID (sieht man auch in den Attributen den Entität).
Wenn sich dabei Überschneidungen ergeben gewinnt die letzte Schnittstellenregistrierung an der CCU.

**Reply by emufan** [reply]
Ich muss doof nachfragen. 🙈Wo Pflege ich den Instanznamen in alter Integration? Und wo Schnittstellennamen?

**Reply by SukramJ** [reply]
Die alte Integration kennt glaube ich nicht diese Unterscheidung.
Ansonsten ist das, glaube ich, der Name des Abschnittes in der config: rf / wired / ip /groups

```
homematic:
  interfaces:
    rf:
      host: 127.0.0.1
      resolvenames: "json"
      username: "Admin"
      password: "secret"
    wired:
      host: 127.0.0.1
      port: 2000
      resolvenames: "json"
      username: "Admin"
      password: "secret"
    ip:
      host: 127.0.0.1
      port: 2010
    groups:
      host: 127.0.0.1
      port: 9292
      resolvenames: "json"
      username: "Admin"
      password: "secret"
      path: /groups
```
