### DISCUSSION TITLE
Add support for HB-LC-Bl1-Velux

### DISCUSSION THREAD

**Discussion by loddi** [SukramJ/aiohomematic#1333] [Ideas]
### The problem

The device HB-LC-Bl1-Velux shows up in Homeassistant, but just has a level attribute. It seems not to be detected as a cover device and does not show any up/down/stop actions.

### What version of HomematicIP (local) has the issue?

1.51.0

```txt
The description of this Homebrew device can be found here:
https://github.com/wolwin/WW-mySHP/tree/master/SHP_HB-LC-BL1-Velux-KLI310

It is supported via the JP-HB-Devices AddOn.
```

**Comment by SukramJ** [comment]
I am not very motivated to implement optimal support for the entire Homebrew devices, since these devices differ all too frequently from the EQ-3 "standards" and require extra treatment.

Basically, however, this is not a problem, since the necessary basic entities should be already provided by the integration.
Building on this, you can implement a complete cover entity yourself with a [cover template](https://www.home-assistant.io/integrations/cover.template/). 

For documentation purposes, you could generate a device description that can be used for this integration.
Instructions can be found [here](https://github.com/danielperna84/custom_homematic?tab=readme-ov-file#homematicip_localexport_device_definition). Otherwise I couldn't help.

**Comment by loddi** [comment]
I totally understand your point. As the code of the homebrew devices might change quite often.

I've already tried to solve this with a cover template. But I haven't managed to get the stop command working. So far my template for this device is:

```
cover:
  - platform: template
    covers:
      dachfenster_flur:
        device_class: shade
        friendly_name: "Dachfenster Flur"
        position_template: "{{states('number.rollade_dachfenster_level') | float}}"
        set_cover_position:
        - service: number.set_value 
          target:
            entity_id: number.rollade_dachfenster_level
          data: 
            value: "{{position|float}}"
        stop_cover:
        - service: homematicip_local.set_device_value
          data:
            device_id: VELUXKLI01
            parameter: STOP
            value: "true"
            value_type: boolean
            channel: 1
```

I would be great if you can help me to sort this out. Using the template might be the most universal solution in the end and documenting it here might help others.

This is the device description:
[HB-LC-Bl1-Velux.json](https://github.com/danielperna84/hahomematic/files/13717512/HB-LC-Bl1-Velux.json)
[HB-LC-Bl1-Velux.json](https://github.com/danielperna84/hahomematic/files/13717515/HB-LC-Bl1-Velux.json)
