### DISCUSSION TITLE
state_class: total für ENERGY_COUNTER, wäre nicht total_increasing "besser"?

### DISCUSSION THREAD

**Discussion by Baxxy13** [SukramJ/aiohomematic#1470] [Q&A]
Ich musste kürzlich mal einen wildgewordenen HmIP-FSM vom Strom trennen, dabei wurde natürlich auch der ENERGY_COUNTER auf '0' gesetzt.
Das HA Energy-Dashboard hat daraufhin die bisher verbrauchte Energie als negativen Wert übernommen was natürlich unschön ist.
![Screenshot 2024-03-28 182944](https://github.com/danielperna84/hahomematic/assets/54898249/4d2b126b-0f37-4260-a568-49be9171dbe2)

Würde es nicht sinnvoller sein die ENERGY_COUNTER als total_increasing zu deklarieren?

**Comment by SukramJ** [comment]
Kannst Du Dir ja mal per HA customize selber einstellen und testen.

Schau dir auch mal die HA [Doku](https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics) dazu an.
Schau dir auch ein entsprechendes [issue](https://github.com/danielperna84/hahomematic/issues/1390) an.

**Reply by Baxxy13** [reply]
Ah ja, danke für die Links und Hinweise.
Wenn ich das geschlossene Ticket richtig deute wurde, um den sporadischen Fehler im Log auszumerzen, state class von 'total_increasing' zu 'total' geändert.
Das erklärt auch warum ich "früher" nach Stromausfall nie solche Ausreißer im Energy-Dashboard hatte.

Die Doku habe ich mir natürlich angesehen, konnte aber für mich nicht abschließend klären welche state class "besser" wäre. 
Tendieren würde ich zu 'total_increasing". Stromausfall kommt zwar eher selten vor, eine HmIP-PSM z.B. zieht man aber ggf. häufiger mal aus der Steckdose.

Ich werde wohl meine 10 FSM's customizen.

**Comment by Baxxy13** [comment]
Also seitdem ich alle ENERGY_COUNTER zu "total_increasing" customized habe ist das Problem nicht mehr aufgetreten.
Zum testen hatte ich einen der FSM's stromlos gemacht um seinen ENERGY_COUNTER auf "0" zu setzen.

Da mir das aber keine Ruhe ließ habe ich an einem HA-Testsystem das Szenario nachgestellt.
Zwei Sensoren die von der selben Quelle gespeist werden, einziger Unterschied die state_class.
```yaml
mqtt:
  sensor:
    - name: Test "Sensor RM27 SysVar MQTT total inc"
      unique_id: test_sensor_rm27_sysvar_mqtt_total_inc
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: "Wh"
      state_topic: "rm27/sysvar/status/6237"
      value_template: "{{ value_json.v }}"
    - name: Test "Sensor RM27 SysVar MQTT total"
      unique_id: test_sensor_rm27_sysvar_mqtt_total
      device_class: energy
      state_class: total
      unit_of_measurement: "Wh"
      state_topic: "rm27/sysvar/status/6237"
      value_template: "{{ value_json.v }}"
``` 

Der Eingangswert wird zyklisch (per kleinem Programm/Script auf der RM) erhöht und für den Test manuell auf "0" gesetzt.
Vor dem "Reset" sieht alles gut aus:
![HA_EnergyDashboard_before_set_zero](https://github.com/danielperna84/hahomematic/assets/54898249/fac7f1ca-f787-41a0-9c9d-5adfe94cb8eb)

Nach dem manuellen Reset auf '0' sieht das so aus:
![HA_EnergyDashboard_after_set_zero](https://github.com/danielperna84/hahomematic/assets/54898249/03ac0dd4-fc2c-42a5-af9e-087bee2673a8)

Der "total_increasing" - Sensor zählt korrekt weiter, der "total" - Sensor liegt nun ziemlich daneben.
