### DISCUSSION TITLE
Not possible to choose active weekprogram for BidCosRF HM-TC-IT-WM-W-EU

### DISCUSSION THREAD

**Discussion by WagnerSystems** [SukramJ/aiohomematic#1708] [General]
Hello,
i can not find a way to choose the active week program for my homematic devices like HM-TC-IT-WM-W-EU.
For my HomematicIP device there is a possibility to show this on the dashboard.

Am i missing something or is this not implemented for HM-TC-IT-WM-W-EU?

**Comment by Baxxy13** [comment]
Also die alten HM-TC-IT-WM-W-EU können 3 Wochenprogramme speichern. (die alten HM-CC-RT-DN leider nur eins)
Eine Möglichkeit die 3 Wochenprogramme zu wechseln hat es nie in die WebUI geschafft und demzufolge kann das auch diese Integration nicht "out-of-the-box" leisten.
Man kann das Wochenprogramm aber in den Geräteeinstellungen des HM-TC-IT-WM-W-EU wechseln und da kommt man auch über eine Aktion von HA aus dran:
```
action: homematicip_local.put_paramset
data:
  device_id: 17e2ec4b65c40e44152609aaa4ef6ac6
  paramset_key: MASTER
  paramset:
    WEEK_PROGRAM_POINTER: 1 
```
Die 3 Programme 1-3 haben die Werte 0-2.

Noch simpler geht es mittels `unignore`.
Dazu den Config-Flow nochmal durchlaufen (konfigurieren), auf der 2.Seite die erweiterte Konfiguration aktivieren und dann auf der 3.Seite den Parameter WEEK_PROGRAM_POINTER reinkopieren und den passenden Eintrag auswählen.
Danach hast du beim HM-TC-IT-WM-W-EU eine zusätzliche "Konfigurations-Entität", ein Drop-Down Feld mit den 3 Wochenprofilen.
