### DISCUSSION TITLE
Improve support for Universal Actuator ELV-SH-WUA / HmIP-WUA 0-10V controller

### DISCUSSION THREAD

**Discussion by mrandt** [SukramJ/aiohomematic#1733] [Ideas]
Hello there,

I am using three Universal Actuator ELV-SH-WUA to control LED panel lights in my office. I believe this is the same hardware controller as the later model HmIP-WUA.

Basically, it has one relay and one analog output that can be used as either 0-10V or 1-10V.

It can be used to control many things; vents, air conditioners, heaters, or - as in my case - lights.

Version 1.65.0 of hahomematic introduced a regular light entity to control both the level in percent as well as the on/off toggle (relay). 

In the next update 1.66.0 this was removed again.

I think these two issues were the main reason for going back:
https://github.com/danielperna84/hahomematic/issues/1656
https://github.com/danielperna84/hahomematic/issues/1720

I would like to start a discussion about how WUA *should* be supported.

I have to say that I liked the light entity with the regular HomeAssistant dimmer control much better. It finally allowed me to integrate the lights into my dashboards and scenes without any extra effort for helpers, automations, etc.

It was also similar to the way Homematic controls WUA in CCU:

![image](https://github.com/user-attachments/assets/98823511-9573-4523-8eb6-5c12391fcc53)

Now we're back to a number entity, which cannot easily be changed by an end user on a dashboard and is cumbersome to include in scenes.

I understand that - depending on the use case - the light entity might not be ideal for others. But in my case the device is in fact used to control lighting.

Could both entities be supported simultaneously? Or could we configure which style we want - number vs. light?

What do others think?

Thanks and best regards
Malte

**Comment by SukramJ** [comment]
You could make it a light by yourself with a [template](https://www.home-assistant.io/integrations/light.template/).

**Comment by mrandt** [comment]
Thanks for the suggestion. I will try that - could be a viable workaround.

I think the WUA device is not as widely used as other HmIP-devices - still I think it's worth considering how this should be supported and controlled in general?!

**Comment by mrandt** [comment]
I have created a template as suggested, works fine for me.

Tricky part was the conversion from 0-255 from brightness control to percent 0-100 in number entity and vice versa. Not sure if the calculation and rounding is the best solution, but it sure is functional.

I am posting the snippet here in case someone else also uses WUA to control lights - needs to be included in configuration.yaml.

```
# template for lights using HmIP-WUA
light:
  - platform: template
    lights:
      buero_deckenlicht_1:
        value_template: "{{ states('number.buro_deckenlicht_1_level_ch2') | int > 0 }}"
        level_template: "{{ (states('number.buro_deckenlicht_1_level_ch2') | float * 2.55) | round(0) }}"
        friendly_name: "Büro Deckenlicht 1"
        turn_on:
          action: number.set_value
          data:
            value: 100.0
          target:
            entity_id: number.buro_deckenlicht_1_level_ch2
        turn_off:
          action: number.set_value
          data:
            value: 0.0
          target:
            entity_id: number.buro_deckenlicht_1_level_ch2
        set_level:
          action: number.set_value
          data:
            value: "{{ (brightness / 2.55) | round(0) }}"
          target:
            entity_id: number.buro_deckenlicht_1_level_ch2
```

**Reply by Tuphal** [reply]
thank you very much!! It took some time to finally find your tempalte.. This is perfectly working for me.
Slightly changed to new syntax.
My config.yaml:

```
# Terrasse Licht als Licht/Dimmer HmIP-WUA
template:
  - light:
    - name: "Terrasse Licht"
      unique_id: Terrasse_Licht
      state: "{{ states('number.terrasse_licht_level_ch2') | int > 0 }}"
      level: "{{ (states('number.terrasse_licht_level_ch2') | float * 2.55) | round(0) }}"
      turn_on:
        action: number.set_value
        data:
          value: 100.0
        target:
          entity_id: number.terrasse_licht_level_ch2
      turn_off:
        action: number.set_value
        data:
          value: 0.0
        target:
          entity_id: number.terrasse_licht_level_ch2
      set_level:
        action: number.set_value
        data:
          value: "{{ (brightness / 2.55) | round(0) }}"
        target:
          entity_id: number.terrasse_licht_level_ch2
```
