### DISCUSSION TITLE
HM-CC-VG-1: Ventilposition „Auf“?

### DISCUSSION THREAD

**Discussion by factory42** [SukramJ/aiohomematic#1757] [Q&A]
Wie kann ich bei einer Heizungsgruppe  HM-CC-VG-1 die Ventilposition „Auf“ (100%) einstellen?

Normalerweise würde man dazu die gewünschte Temperatur 30.5 einstellen. Das ist aber außerhalb des Wertebereichs. Für die Ventilposition „Zu“ gibt es den „Off“-Modus. Hier fehlt anscheinen ein „On“-Modus.

**Comment by stuckis6er** [comment]
Hallo,

nur so eine Idee. Schalte doch mal auf manuell und dann auf 30,5°C.

**Reply by factory42** [reply]
So würde man das machen. Geht leider nicht, weil der Wertebereich eingeschränkt ist. Maximal 30 bei der Temperatur.

**Reply by Baxxy13** [reply]
Ja, da hat eQ-3 den Maximalwert verbockt. Der sollte 30.5 sein (statt 30.0)
Die Integration richtet sich nach den Vorgaben, ist also unschuldig.

Als Workaround kannst du den Wert über eine Aktion setzen, bspw. so:
```
action: homematicip_local.set_device_value
data:
  device_id: 11d217158aad81d5f1a4190d885e396a
  channel: 1
  parameter: MANU_MODE
  value: "30.5"
  value_type: double
```

Die device_id gehört hier zu einer HM-Heizgruppe, lässt sich im UI-Modus auswählen und reinklicken.

**Reply by factory42** [reply]
Ja, danke.

Jetzt kommt allerdings diese Fehlermeldung:

SET_VALUE failed with HaHomematicException [Parameter MANU_MODE could not be found: Zik CCU-VirtualDevices/INT0000010:1/VALUES]: INT0000010:1, MANU_MODE, 30.5

Tut mir leid. Bin nicht so befreundet mit dem Homematic-Zeugs.

**Reply by factory42** [reply]
Ich habe zwei CCUs und entsprechend auch zwei Verbindungen konfiguriert. Kann es daran liegen? Der Name "Zik CCU" deutet darauf hin. Das wäre die falsche Verbindung.

**Reply by Baxxy13** [reply]
Das Gerät wird ja über die `device_id` angesprochen. 
Die ist eindeutig und einmalig. 
Wenn also der Befehl an die falsche (Zik CCU) Zentrale rausging dann hast du ein Gruppengerät von dieser Zentrale ausgewählt.
Und das war vermutlich eine HmIP-Heizgruppe welche den Parameter `MANU_MODE` nicht hat.

Gegen solche Verwechselungen helfen gute Namen weil ja die Seriennummer `INT0000010` auf mehreren Zentralen existieren kann und man auch nicht unterscheiden kann ob es sich um eine HM / HmIP - Heizgruppe handelt.

**Reply by factory42** [reply]
Ich habe es noch mit einer anderen Heizungsgruppe ausprobiert. Selbes Fehlerbild.

Und ich benutze schon sprechende Namen. Die werden bei der Fehlermeldung aber anscheinend auf die Seriennummer umgemünzt.

Ich denke, der Befehl wird an die falsche Verbindung geschickt. Auf meiner zweiten Verbindung gibt es auch Heizungsgruppen. Allerdings tatsächlich HmIP. Daher der Fehler.

Kurz im template-Editor ausprobiert:
```
        {{ device_id("climate.vogelherd_treppe_heizung")
           + ", "
           + state_attr('climate.vogelherd_treppe_heizung', 'interface_id')   
        }}
```

Ergibt:
`9d94d0c1303b0b03bbed5d245dc7fc71, Vog CCU-VirtualDevices`

Im Aktionseditor:
```
action: homematicip_local.set_device_value
data:
  channel: 1
  parameter: "MANU_MODE"
  value: "30.5"
  value_type: double
  device_id: "9d94d0c1303b0b03bbed5d245dc7fc71"
```
Ergibt Fehlermeldung:
`SET_VALUE failed with HaHomematicException [Parameter MANU_MODE could not be found: Zik CCU-VirtualDevices/INT0000006:1/VALUES]: INT0000006:1, MANU_MODE, 30.5`

`Zik CCU-VirtualDevices` ist die zweite CCU
