### DISCUSSION TITLE
Unterstützung für HmIP-WRCD

### DISCUSSION THREAD

**Discussion by eikowagenknecht** [SukramJ/aiohomematic#176] [Ideas]
Ausgelagert auf Wunsch von @SukramJ unter https://github.com/danielperna84/hahomematic/discussions/127#discussioncomment-1963143 :-)

Ich habe jetzt auch mal den Displaytaster (-WRCD) getestet. Ich kann erfolgreich an ihn senden: 
![image](https://user-images.githubusercontent.com/1475672/149353299-27983a25-9c6f-4e3d-8999-0d8f24d437e7.png)

Das ist natürlich schon arg technisch und ich habe es auch nur rausgefunden, wie genau ich senden muss, weil mein openHAB mich drauf gestoßen hat: 
![image](https://user-images.githubusercontent.com/1475672/149353413-b64bc119-2638-4b7e-b030-6221293b56fe.png)

Meinst du das kann man ggf. noch etwas schöner integrieren mit hahomematic? Hier die Debugdaten, falls du sie benötigst:
[wrcd.zip](https://github.com/danielperna84/hahomematic/files/7863691/wrcd.zip)

**Comment by eikowagenknecht** [comment]
Wer schnell eine Lösung will um einfach nur Text auf den Taster zu bekommen: Skript anlegen (und die ***** durch die Device ID ersetzen). Die ID bekommt ihr, wenn ihr z.B. in den Entwicklerwerkzeugen das Gerät für einen Service auswählt und dann in den YAML Modus wechselt, z.B.:
![image](https://user-images.githubusercontent.com/1475672/149356957-58d52984-278d-4379-9e92-836f03ba7fde.png)

Vielleicht geht's auch irgendwo noch schneller, aber das funktioniert auf jeden Fall.

Hier das Skript, setzt die Zeilen einfach linksbündig.

```
service: homematicip_local.set_device_value
data:
  device_id: **********
  channel: 3
  parameter: COMBINED_PARAMETER
  value: >-
    {DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=LEFT,DDS={{Zeile1}},DDID=1},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=LEFT,DDS={{Zeile2}},DDID=2},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=LEFT,DDS={{Zeile3}},DDID=3},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=LEFT,DDS={{Zeile4}},DDID=4},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=LEFT,DDS={{Zeile5}},DDID=5,DDC=true}

```


Beispielaufruf:
```
service: script.eg_flur_displaytaster_setzen
data:
  Zeile1: "10010111011001"
  Zeile2: "00101001101101"
  Zeile3: "11010010100101"
  Zeile4: "11010100010100"
  Zeile5: "01010010100100"

```

**Reply by eikowagenknecht** [reply]
Und hier noch meine Notizen zur bekloppten Syntax des Gerätes:

	// DDBC = BackgroundColor, (WHITE, BLACK)
	// DDTC = TextColor (WHITE, BLACK)
	// DDI =  Image
	//	0 = Nicht benutzt
	//	1 = Lampe aus
	//	2 = Lampe ein
	//	3 = Schloss auf
	//	4 = Schloss zu
	//	5 = X 
	//	6 = Häckchen
	//	7 = Info
	//	8 = Briefumschlag
	//	9 = Schraubenschlüssel
	//	10 = Sonne
	//	11 = Mond
	//	12 = Wind
	//	13 = Wolke
	//	14 = Wolke/Blitz
	//	15 = Wolke/leichter Regen
	//	16 = Wolke/Mond
	//	17 = Wolke/Regen
	//	18 = Wolke/Schnee
	//	19 = Wolke/Sonne
	//	20 = Wolke/Sonne/Regen
	//	21 = Wolke/Schneeflocke
	//	22 = Wolke/Regentropfen
	//	23 = Flamme
	//	24 = Fenster auf
	//	25 = Rollladen
	//	26 = Eco
	//	27 = Unscharf
	//	28 = Hüllschutz
	//	29 = Vollschutz
	//	30 = Benachrichtigung
	//	31 = Uhr
	// DDA = TextAlign (CENTER, LEFT, RIGHT)
	// DDS = Textstring max 14 Zeichen ohne Bild, danach wird automatisch hinten abgeschnitten. Bei Bild in der Zeile: max.11, danach wird automatisch vorne abgeschnitten
	// DDID = Textzeile (1,2,3,4,5)
	// DDC = Commit = Ausführung

	// ANS = Sound
	//	-1 = Nicht benutzt (funktioniert nicht? stattdessen muss man meiner Erfahrung nach den ganzen Block weglassen)
	//	0 = Batterie leer, kurz-kurz-kurz
	//	1 = Alarm aus,  lang-kurz
	//	2 = Externer Alarm aktiviert, lang-kurz-kurz
	//	3 = Interner Alarm aktiviert, lang-kurz
	//	4 = Externer Alarm verzögert aktiviert, kurz-kurz
	//	5 = Interner Alarm verzögert aktiviert, kurz
	//	7 = Fehler, lang
	//	6 = Event, mittel
	// R = Repetiton Wiederholung (0 = insgesamt einmal)
	// IN = Intervall Abstand Töne
	
	// Beispiel:
	// "{DDBC=WHITE,DDTC=BLACK,DDI=1,DDA=CENTER,DDS=Zeile1,DDID=1},{DDBC=WHITE,DDTC=BLACK,DDI=2,DDA=CENTER,DDS=Zeile2,DDID=2},{DDBC=WHITE,DDTC=BLACK,DDI=3,DDA=CENTER,DDS=Zeile3,DDID=3},{DDBC=WHITE,DDTC=BLACK,DDI=5,DDA=CENTER,DDS=Zeile4,DDID=4},{DDBC=WHITE,DDTC=BLACK,DDI=3,DDA=CENTER,DDS=Zeile5,DDID=5,DDC=true},{R=1,IN=5,ANS=3}"

Vielleicht schreibe ich da bald nochmal einen Blogbeitrag zu, so wirklich toll dokumentiert ist es bisher ja nicht :D

**Reply by eikowagenknecht** [reply]
@SukramJ: Bzgl. der Use cases:
- Sound nach Tasterdruck abspielen, um Erfolg oder Miserfolg zu signalisieren (mit dem ANS Parameter)
- Sicherheitsstatus anzeigen (Alle Fenster zu, Türen abgeschlossen, ...). Bei mir hängt das Teil am Ausgang und dient quasi als "Haus verlassen" Schalter.
- Status der damit geschalteten Lichter (z.B. Helligkeit in %) anzeigen
- Beliebige andere Statuswerte anzeigen (z.B. Stromverbrauch heute, Wetter morgen, ..., quasi als Mini Dashboard)

**Reply by noxhirsch** [reply]
@eikowagenknecht Seit der vorletzten HA Version gibt es Blueprints für Skripte. Vielleicht wäre das hier die einfachste Lösung?
(nur so als Idee - ich selbst habe das Gerät nicht)

**Reply by eikowagenknecht** [reply]
@noxhirsch Durchaus möglich, bisher habe ich mich noch nicht ausführlich mit Blueprints beschäftigt. Ich schaue mir das bei Gelegenheit mal an. Es wird aber auf jeden Fall eine Herausforderung, alle Möglichkeiten dieser doch sehr speziellen Syntax dort abzubilden. Der einfache Fall "nur Text" wird aber sicher möglich sein.

**Reply by emufan** [reply]
Hast Du auch Fotos vom Output? Mich würde interessieren, wie das dann bei Dir aussieht, ob es nur mit oder auch ohne Striche geht, usw. Die Fotos im Netz sind da recht uneindeutig.

**Reply by eikowagenknecht** [reply]
> Hast Du auch Fotos vom Output? Mich würde interessieren, wie das dann bei Dir aussieht, ob es nur mit oder auch ohne Striche geht, usw. Die Fotos im Netz sind da recht uneindeutig. 

Es geht auch ohne Striche. Mein Beispiel von oben erzeugt folgenden Output:

![image](https://user-images.githubusercontent.com/1475672/149411057-247c4e92-23b7-4727-9bf3-59fef3e90eb2.jpeg)

**Reply by SukramJ** [reply]
@eikowagenknecht Hast du dir schon mal Gedanken gemacht, wie eine Integration in HA aussehen könnte?

**Comment by fridomac** [comment]
Ich habe auch so ein Ding eingebunden und würde es gerne neben der Haustür als "Fenster offen"-Statusdisplay anbringen. 
Hat jemand sowas schonmal gebaut? Oder doch lieber verkaufen und ESP+e-Ink-Display dafür hinbauen?
Gruß, Frido.

**Reply by eikowagenknecht** [reply]
Funktioniert einwandfrei, du kannst meine Skripte von weiter oben nehmen und damit in die 5 Zeilen beliebigen Text reinschreiben, u.a. auch wie viele (oder welche) Fenster offen sind.

**Reply by fridomac** [reply]
Geht klar, vielen Dank, als Umsteiger von OpenHAB muss ich das erstmal lernen, HA ist eine andere Welt!

**Reply by PottiMc** [reply]
@eikowagenknecht @fridomac 
Hallo, wie habt ihr es hinbekommen, die Werte eurer Sensoren auf dem Display darzustellen?
In Openhab und über Blockly war das kein Problem, in Home Assistant finde ich allerdings bisher keine Möglichkeit. Kann mir vielleicht jemand weiterhelfen?

**Reply by eikowagenknecht** [reply]
Siehe mein Skript weiter oben.

**Reply by PottiMc** [reply]
Danke dir für die schnelle Antwort. Das Skript habe ich verstanden und umgesetzt und kann dort auch manuell Text einfügen. Wie bringe ich den Wert von Variablen, bspw. sensor.aussentemperatur (10°C) rein?

**Reply by eikowagenknecht** [reply]
Siehe meine Antwort an @fridomac unten :-)

**Comment by fridomac** [comment]
Ich hatte das damals nicht weiter verfolgt, kriege es aber auch immer noch nicht hin:
Ich lege das Script als Script an, erstelle dann eine Automation, bei der ich das Script als Servixmce aufrufe,,aber wie kriege ich die Variablen „Zeile1“ bis „Zeile4“ in der Automation übergeben?

**Reply by eikowagenknecht** [reply]
So wie bei allen anderen Skripten auch, einfach im Serviceaufruf die Template Logik verwenden. Viele Beispiele gibt es z.B. hier: https://www.home-assistant.io/docs/configuration/templating/

Z.B. würde `{{ states("light.eg_schlafen_hue_decke") }}` (statt "10001010101010") in meinem Beispiel oben in `off` resultieren.

**Reply by PottiMc** [reply]
Dann verstehe ich leider nicht was ich falsch mache?

Statischer Text geht problemfrei durch. 
Probiert mit folgenden Varianten:
  Zeile1: {{ states("light.buro") }}
  Zeile1: "{{ states("light.buro") }}"

Wechsele ich nach Ausführung des Skripts in den YAML Modus steht dort sogar tatsächlich "[object Object]": null

![PXL_20240229_071455673](https://github.com/danielperna84/hahomematic/assets/39881308/c2e86028-6b0b-4719-95d5-530725e17115)

```
alias: Senden an Display
sequence:
  - service: script.wandtasterdisplay
    data:
      Zeile1:
        "[object Object]": null
      Zeile2: "00101001101101"
      Zeile3: "11010010100101"
      Zeile4: "11010100010100"
      Zeile5: "01010010100100"
fields: {}
mode: single
```



Übernehme ich genau die gleiche Zeile in den Template-Editor kommt "off" raus.
![image](https://github.com/danielperna84/hahomematic/assets/39881308/2b785931-e8b0-4dd2-bc42-db182d97bb42)

Danke noch für den Link zum Templating!

**Reply by eikowagenknecht** [reply]
Da sind falsche Anführungszeichen im Text. An manchen Stellen ist es da zickig, wenn sie nicht richtig escaped werden. `'{{ states("light.buro" }}'` ginge (wird automatisch beim Speichern zu `"{{ states(\"light.buro\" }}"`) ;-)

**Comment by PottiMc** [comment]
Danke! Endlich funktioniert es mal ansatzweise wieder so wie in Openhab. Der Editor ist wirklich zickig.

![PXL_20240229_135540434](https://github.com/danielperna84/hahomematic/assets/39881308/01386e64-ef19-4d83-ab7b-8b044962531d)


Hier mein Code für die Nachwelt:

```
service: script.wandtasterdisplay
data:
  Zeile1: "Aktuell "
  Zeile2: >-
    {{ (states("sensor.tasmota_aussenfuehler_bme280_temperature") | float ) }}
    ^C
  Zeile3: "Vorhersage "
  Zeile4: >-
    {{ (state_attr('weather.forecast_home', 'forecast')[0].templow | float |
    round (0)) }}^C / {{ (state_attr('weather.forecast_home',
    'forecast')[0].temperature | float | round(0)) }}^C
  Zeile5: >-
    Regen: {{ (state_attr('weather.forecast_home', 'forecast')[0].precipitation
    | float | round (0)) }} mm

```

```
service: homematicip_local.set_device_value
data:
  device_id: XXXXXXXX
  channel: 3
  parameter: COMBINED_PARAMETER
  value: >-
    {DDBC=WHITE,DDTC=BLACK,DDI=19,DDA=CENTER,DDS={{Zeile1}},DDID=1},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile2}},DDID=2},{DDBC=WHITE,DDTC=BLACK,DDI=10,DDA=CENTER,DDS={{Zeile3}},DDID=3},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile4}},DDID=4},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile5}},DDID=5,DDC=true}

```

**Reply by eikowagenknecht** [reply]
Danke, ich glaube das übernehme ich. Bei mir hängt der Schalter am Ausgang und bisher hatte ich noch keine schöne Beschriftung :-)

**Reply by emufan** [reply]
Die weather-forecast-Attribute werden nicht mehr lange funktionieren. Könnt Ihr Euch beizeiten schon einmal mit befassen. Müssen in Zukunft erst mal gelesen und dann verwendet werden.

**Reply by PottiMc** [reply]
Stimmt, da hast du recht mit den Forecast-Attributen. Hier der angepasste Code:

```
service: homematicip_local.set_device_value
data:
  device_id: XXXXXXX
  channel: 3
  parameter: COMBINED_PARAMETER
  value: >-
    {DDBC=WHITE,DDTC=BLACK,DDI=19,DDA=CENTER,DDS={{Zeile1}},DDID=1},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile2}},DDID=2},{DDBC=WHITE,DDTC=BLACK,DDI=10,DDA=CENTER,DDS={{Zeile3}},DDID=3},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile4}},DDID=4},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile5}},DDID=5,DDC=true}
```

```
service: script.wandtasterdisplay
data:
  Zeile1: "Aktuell "
  Zeile2: "{{ (states(\"sensor.tasmota_aussenfuehler_bme280_temperature\") | float ) }}^C"
  Zeile3: "Vorhersage "
  Zeile4: >-
   {{ (states('sensor.forecast_temperature_low') | float | round(0)) }}^C / {{ (states('sensor.forecast_temperature') | float | round(0)) }}^C
  Zeile5: >-
    Regen: {{ (states('sensor.weather_forecast_precipitation') | float | round (0)) }} mm

```

Natürlich braucht man das entsprechende Template in der template.yaml:
Ich lese nur die Vorhersagewerte aus, daher reicht mir das 59-minütige Intervall. Wer aktuelle Werte möchte sollte das natürlich öfter laufen lassen und das time-pattern abändern.

```
#Wetter
- trigger:
  - platform: state
    entity_id: 
    - weather.home
  - platform: event
    event_type: event_template_reloaded
  - platform: time_pattern
    minutes: "/59"
  action:
    - service: weather.get_forecasts
      data:
        type: daily
      target:
        entity_id: weather.home
      response_variable: daily
    - variables:
        daily_forecast: "{{ daily['weather.home'].forecast }}"
  sensor:
  - unique_id: weather_forecast_temp
    name: Forecast temperature
    unit_of_measurement: '°C'
    state: "{{ daily_forecast[0].temperature }}"
    device_class: temperature
    attributes:
      time: "{{ daily_forecast[0].datetime }}"
      forecast: "{{ daily_forecast | map(attribute='temperature') | list }}"
  - unique_id: weather_forecast_templow
    name: Forecast temperature low
    unit_of_measurement: '°C'
    state: "{{ daily_forecast[0].templow }}"
    device_class: temperature
    attributes:
      time: "{{ daily_forecast[0].datetime }}"
      forecast: "{{ daily_forecast | map(attribute='templow') | list }}"
  - unique_id: weather_forecast_wind_speed
    name: weather Forecast wind speed
    unit_of_measurement: 'km/h'
    state: "{{ daily_forecast[0].wind_speed }}"
    device_class: wind_speed
    attributes:
      time: "{{ daily_forecast[0].datetime }}"
      forecast: "{{ daily_forecast | map(attribute='wind_speed') | list }}"
  - unique_id: weather_forecast_precipitation
    name: weather Forecast precipitation
    unit_of_measurement: 'mm'
    state: "{{ daily_forecast[0].precipitation }}"
    device_class: precipitation
    attributes:
      time: "{{ daily_forecast[0].datetime }}"
      forecast: "{{ daily_forecast | map(attribute='precipitation') | list }}"
```





Bei mir ist das so geregelt, dass bis 18 Uhr die Wetter"vorhersage" des heutigen Tages angezeigt wird und ab 18 Uhr die Vorhersage für den nächsten Tag. Der Wechsel geschieht mittels Automatisierungen und 2 Skripten. Mit den Push-Buttons kann man dann noch andere Dinge anzeigen lassen.

**Reply by eikowagenknecht** [reply]
Super, danke! Wie hast du das mit den Wettersymbolen gelöst? Wo machst du die Unterscheidung mit den 18 Uhr? Werden die bei dir abhängig vom Forecast gesteuert oder sind die fix? Und was sind die anderen Dinge, die du anzeigen lässt? :-)

**Reply by PottiMc** [reply]
Noch sind die fix. Werde ich die Tage noch ergänzen.
Die Unterscheidung 18-6 Uhr und 6-18 Uhr erfolgt einfach durch eine Automatisierung und den Aufruf verschiedener "Zeile1-Zeile5"-Skripte. Das Grundskript mit "homematicip_local.set_device_value" bleibt (noch) immer gleich.
Auf den Knöpfen als kurzer Tastendruck hatte ich (in Openhab) den ausführlichen Regenbericht der nächsten 3 Stunden für die Gassi-Runde und den Zustand der Fensterkontakte und des Garagentors (das ist nicht in Sichtweite um die Ecke). Also eher Nebenfunktionen. Wenn man heimkam wurde gewechselt auf wichtige Meldungen á la "Waschmaschine fertig", "Mülltonne muss raus", usw.

Langer Tastendruck hat dann Dinge geschaltet, aber das Display nicht geändert.

Jetzt steht das Display aber im Bad und ich werde das nicht mehr so ausführlich machen. Der Wetterbericht reicht, um sich morgens entsprechend anzuziehen und abends um ggf. die Klamotten rauszulegen.

Jetzt wo das grundlegende (dank deiner Hilfe!) passt ist der Rest Fleißarbeit über die nächste Zeit.

**Reply by eikowagenknecht** [reply]
Super, danke für den ausführlichen Bericht :-)

Ich habe es jetzt wie folgt eingerichtet:

Automatisationen:
```yaml
alias: Displaytaster tagsüber
description: ""
trigger:
  - platform: time
    at: "07:00:00"
  - platform: time
    at: "08:00:00"
  - platform: time
    at: "09:00:00"
  - platform: time
    at: "10:00:00"
  - platform: time
    at: "11:00:00"
  - platform: time
    at: "12:00:00"
  - platform: time
    at: "13:00:00"
  - platform: time
    at: "14:00:00"
  - platform: time
    at: "15:00:00"
  - platform: time
    at: "16:00:00"
  - platform: time
    at: "17:00:00"
condition: []
action:
  - service: script.displaytaster_wetter
    metadata: {}
    data: {}
mode: single
```

Zugehöriges Skript:

```yaml
alias: Displaytaster Wetter Heute
sequence:
  - variables:
      IconHeute: >-
        {{ { 'clear-night': 16, 'cloudy': 13, 'fog': 13, 'hail': 23,
        'lightning': 14, 'lightning-rainy': 14, 'partlycloudy': 19, 'pouring':
        17, 'rainy': 15, 'snowy': 18, 'snowy-rainy': 18, 'sunny': 10, 'windy':
        12, 'windy-variant': 12, 'exceptional': 22, }.get(
        states('sensor.wetter_heute'), 0 ) }}
  - variables:
      Zeile1: AKTUELL
      Zeile2: >-
        {{ (states("sensor.au_garten_wettersensor_temperatur") | float |
        round(1) ) }}^C 
      Zeile3: >-
        {{ (states('sensor.wetter_heute_temperatur_min') | float | round(1))
        }}^C-{{ (states('sensor.wetter_heute_temperatur') | float | round(1))
        }}^C
      Zeile4: "{{ (states(\"sensor.wetter_heute_niederschlag\") | float | round (0))}} mm"
      Zeile5: HEUTE ({{ (now().day | string + '.') }})
  - service: homematicip_local.set_device_value
    data:
      device_id: fc66c7b2b438a75f16556c0f2e89697f
      channel: 3
      parameter: COMBINED_PARAMETER
      value: >-
        {DDBC=BLACK,DDTC=WHITE,DDI=0,DDA=CENTER,DDS={{Zeile1}},DDID=1},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile2}},DDID=2},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile3}},DDID=3},{DDBC=WHITE,DDTC=BLACK,DDI={{IconHeute}},DDA=CENTER,DDS={{Zeile4}}
        ,DDID=4},{DDBC=BLACK,DDTC=WHITE,DDI=0,DDA=CENTER,DDS={{Zeile5}},DDID=5,DDC=true}
mode: single
```

```yaml
alias: Displaytaster abends
description: ""
trigger:
  - platform: time
    at: "18:00:00"
  - platform: time
    at: "19:00:00"
  - platform: time
    at: "20:00:00"
  - platform: time
    at: "21:00:00"
  - platform: time
    at: "22:00:00"
  - platform: time
    at: "23:00:00"
  - platform: time
    at: "23:59:00"
condition:
  - condition: state
    entity_id: input_boolean.schlafmodus
    state: "off"
action:
  - service: script.displaytaster_wetter_morgen
    data: {}
mode: single
```

Zugehöriges Skript:
```yaml
alias: Displaytaster Wetter Morgen
sequence:
  - variables:
      IconMorgen: >-
        {{ { 'clear-night': 16, 'cloudy': 13, 'fog': 13, 'hail': 23,
        'lightning': 14, 'lightning-rainy': 14, 'partlycloudy': 19, 'pouring':
        17, 'rainy': 15, 'snowy': 18, 'snowy-rainy': 18, 'sunny': 10, 'windy':
        12, 'windy-variant': 12, 'exceptional': 22, }.get(
        states('sensor.wetter_morgen'), 0 ) }}
  - variables:
      Zeile1: AKTUELL
      Zeile2: >-
        {{ (states("sensor.au_garten_wettersensor_temperatur") | float |
        round(1) ) }}^C 
      Zeile3: >-
        {{ (states('sensor.wetter_morgen_temperatur_min') | float | round(1))
        }}^C-{{ (states('sensor.wetter_morgen_temperatur') | float | round(1))
        }}^C
      Zeile4: >-
        {{ (states("sensor.wetter_morgen_niederschlag") | float | round (0))}}
        mm
      Zeile5: MORGEN ({{ (now() + timedelta(days=1)).day | string + '.' }})
  - service: homematicip_local.set_device_value
    data:
      device_id: fc66c7b2b438a75f16556c0f2e89697f
      channel: 3
      parameter: COMBINED_PARAMETER
      value: >-
        {DDBC=BLACK,DDTC=WHITE,DDI=0,DDA=CENTER,DDS={{Zeile1}},DDID=1},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile2}},DDID=2},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS={{Zeile3}},DDID=3},{DDBC=WHITE,DDTC=BLACK,DDI={{IconMorgen}},DDA=CENTER,DDS={{Zeile4}}
        ,DDID=4},{DDBC=BLACK,DDTC=WHITE,DDI=0,DDA=CENTER,DDS={{Zeile5}},DDID=5,DDC=true}
mode: single
```

Damit bekommt die Zeile nun auch ein Wettersymbol passend zur Vorhersage (heute oder morgen).
