### DISCUSSION TITLE
Temperature change trigger does not trigger

### DISCUSSION THREAD

**Discussion by bblaha** [SukramJ/aiohomematic#1791] [General]
### I agree to the following

- [x] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I created an automation with a trigger for the thermostat temperature being set over 25°C.
The automation never gets triggered, no matter what I set the temperature to.

Below is the minimalized variant of my trigger:
`description: ""
mode: single
triggers:
  - type: temperature
    device_id: 3587b856dafb16fedcb4682f326a21c8
    entity_id: 92f8bfe1067c145d7c21e3901cf7a3f9
    domain: sensor
    trigger: device
    above: 25
    id: Temp Above 25
conditions: []
actions: []`

### What version of HomematicIP (local) has the issue?

1.68,0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
I cannot provide logs as there is no error, I just cannot get the trigger to actually trigger
```

**Comment by SukramJ** [comment]
Das ist hier kein HA Support Forum. 
Wenn die Temperaturanzeige über 25 C steigt dann ist das aus Integrationssicht abgeschlossen.

Bei mir funktioniert folgende Automatisierung:

```
alias: Heizung KH ausschalten
description: ""
triggers:
  - type: temperature
    device_id: 97aa53ebc8c4f12ee7e67783aa9ac67d
    entity_id: 59499ba50f9cb8a88272fd068b46b137
    domain: sensor
    trigger: device
    above: 15
conditions: []
actions:
  - type: turn_off
    device_id: a8790c195ebadbabd51bd42b656fd445
    entity_id: 35c2c2e0b324ff3581d61418a271164f
    domain: switch
mode: single
```

**Comment by bblaha** [comment]
Thank you for your reply. I was not asking for HA support. In my understanding, the add-on should trigger when the set temperature is set above 25°C. It does not, hence my assumption that there is a problem with the add-on.

This could be very well due to a wrong setup on my side, but I was not asking for tips on how to create the automation I want, I was - and still am - assuming that there is a problem with the add-on.

**Comment by SukramJ** [comment]
> Wenn die Temperaturanzeige über 25 C steigt dann ist das aus Integrationssicht abgeschlossen.

Ist das der Fall?  ja oder nein

**Comment by bblaha** [comment]
Yes, the widget shows the set temperature as being set above 25°C. So what you are saying is the triggers are out of scope for this add-on? Where is the best place to address this, then?

**Comment by bf8392** [comment]
Hi, I just stumbled upon this issue and tested the same setup...(trigger when temperature is above 10 degrees). I also tried with different tempertures and blow on the thermostat to get it above for verifying...My Action also never triggers and it only happens for this integration...I'm quite sure that the temperature in my living room is above 10 degrees so maybe the Problem is in the integration?

**Reply by SukramJ** [reply]
Was soll ich mit solchen Geschichten anfangen?
Bei mir funktioniert es wird dir auch wenig helfen oder?
Liefert doch mal konkrete Information:
- Ein **korrekt** formatiertes YAML der Automatisierung.
- Die Temperaturkurve des Sensors der als Trigger verwendet wird.

**Reply by bblaha** [reply]
> Was soll ich mit solchen Geschichten anfangen? Bei mir funktioniert es wird dir auch wenig helfen oder? Liefert doch mal konkrete Information:
> 
> * Ein **korrekt** formatiertes YAML der Automatisierung.
> * Die Temperaturkurve des Sensors der als Trigger verwendet wird.

Maybe it comes across wrong in translation, but I don't feel there is a need for that kind of hostility. I - and apparently @bf8392 as well - want to find out what is wrong, and if this is in no relation to your integration, then that is great and I will go on looking for the cause. If it is, I would like to contribute to solving the problem to the best of my capacity.

I am trying to deliver what you are asking from my side, but first I would like to clarify:
The MEASURED temperature should not be of concern here. My understanding is that there are two triggers:
1) Device measured temperature changed - My understanding is that this triggers, when the temperature measured by the thermostat (which is a wall thermostat 150628A0) changes above or below a threshold
2) Device Temperature temperature changed (yes, it is worded that way) - My understanding is that this triggers, when the temperature SET on the thermostat changes above or below a certain threshold.

Maybe I misunderstand this and there IS no trigger for temperature set (in which case the difference between temperature changed and temperature measured triggers is unclear), anyway: I am using trigger #2, so I expect it to trigger, when the temperature is changed. This trigger never happens.

As you asked for a correctly formatted YAML, I am trying to provide the entire automation here:
```
`alias: Thermostat Limits
description: ""
triggers:
  - type: temperature
    device_id: 3587b856dafb16fedcb4682f326a21c8
    entity_id: 92f8bfe1067c145d7c21e3901cf7a3f9
    domain: sensor
    trigger: device
    above: 25
    id: Temp Above 25
  - type: temperature
    device_id: 3587b856dafb16fedcb4682f326a21c8
    entity_id: 92f8bfe1067c145d7c21e3901cf7a3f9
    domain: sensor
    trigger: device
    id: Temp Below 18
    below: 18
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Temp Above 25
        sequence:
          - action: climate.set_temperature
            metadata: {}
            data:
              temperature: 25
            target:
              device_id: 3587b856dafb16fedcb4682f326a21c8
      - conditions:
          - condition: trigger
            id:
              - Temp Below 18
        sequence:
          - action: climate.set_temperature
            metadata: {}
            data:
              temperature: 18
            target:
              device_id: 3587b856dafb16fedcb4682f326a21c8
mode: single
`
```
As for the temperature curve, see below. There is one point where each trigger should have triggered, alas it has not.
![temperature curve](https://github.com/user-attachments/assets/4d05b338-d7d9-47d2-9774-3eb8be6ad561)

So, maybe you could kindly let me know if I misunderstand the purpose of these separate triggers and there just is no "Set temperature changed" trigger or if there is a flaw in my automation or the integration.
