### DISCUSSION TITLE
"Unerreichbar" Geräte reaktivieren Teil 2

### DISCUSSION THREAD

**Discussion by emufan** [SukramJ/aiohomematic#1951] [Q&A]
Hat sich seit https://github.com/SukramJ/hahomematic/discussions/566#discussioncomment-3456612 eigentlich etwas verändert, was ich trotz längerer Suche aktuell nicht finden konnte? Seit einiger Zeit (hier letzte Ausfügrung 08.11., aber leider weiß ich nicht wann ich welche Integrations-Updates ausgeführt habe), auf der CCU gab es aber keine Updated seither) wird bei mir die Automation nicht mehr ausgeführt:

```
alias: HMIP Verbindungsfehler HmIP-BROLL
description: ""
mode: queued
max: 10
triggers:
  - event_type: homematic.device_availability
    event_data:
      device_type: HmIP-BROLL
      unavailable: true
    trigger: event
conditions: []
actions:
  - data:
      device_id: "{{ trigger.event.data.device_id }}"
    action: homematicip_local.force_device_availability
```

Hat sich da etwas verändert oder hat jemand eine Idee, dass das nicht mehr getriggert wird? Klappte vorher fantastisch und nun bleiben die BROLLs nun deaktivert, wenn sie mal nicht erreichbar sind.

**Comment by SukramJ** [comment]
Ändere mal `device_type` auf `model`. Das hat sich mit der 1.66.0 geändert.

**Comment by emufan** [comment]
Oh no. Das habe ich tatsächlich übersehen und nun gefunden, bzw. den Kontext nicht erkannt. Danke Dir.

Habe nun auch mit dem allgemeindem Trigger vergleichen, der schon noch die nicht-erreichbarkeit gemeldet hatte und dort entsprechend Deiner Info auch gefunden, dass da kein `device_type` mehr geliefert wird, sondern `model`. Danke Dir.

```
    event_type: homematic.device_availability
    data:
      address: xxx
      channel_no: 0
      model: HmIP-BROLL
      interface_id: Homematic-HmIP-RF
      parameter: UNREACH
      value: true
      device_id: xxx
      name: Rollladen Küchentür
      identifier: xxx_DEVICE_AVAILABILITY
      title: HOMEMATICIP_LOCAL Device not reachable
      message: Rollladen Küchentür/xxx on interface Homematic-HmIP-RF
      unavailable: true
```

Hätte ich auch selber drauf kommen, dass zuerst mal zu vergleichen. Sorry. Und nochmals danke.
