### DISCUSSION TITLE
hahm.put_paramset liefert ProxyException

### DISCUSSION THREAD

**Discussion by AlexaMiller** [SukramJ/aiohomematic#217] [Q&A] [answered]
Servus,

bitte um Unterstützung beim Aufrufen eines Dienstes - ich würde gerne einen HmIP-PSM Stecker für 5 sec auf "on" schalten.

service: hahm.put_paramset
data:
  channel: 3
  paramset_key: VALUES
  paramset:
    ON_TIME: '5'
    STATE: true
  device_id: b23fadaafaa421e4122f8031ce9a194e

Liefert beim Aufruf über die Entwicklerwerkzeuge im Log: 
put_paramset failed: ProxyException: 0001DBE9A61A2E:3, VALUES, {'ON_TIME': '5', 'STATE': True}

Bitte um einen Hinweis wo ich falsch abgebogen bin, 
(die device_id hat lovelace->yaml selbständig aus dem Gerät gezogen).

Liebe Grüße, Alexa

**Comment by SukramJ** [comment, marked as answer]
Ich würde über die Entwicklerwerkzeuge gehen. Service hahm.put_paramset auswählen. Da kannst du auch das Gerät auswählen.
Ich hab eine HmIP-BSM verwendet, daher channel 4.
Das ist mein funktionierender yaml Code:

```
service: hahm.put_paramset
data:
  channel: 4
  paramset_key: VALUES
  device_id: 432a95f06823aecbb33752399282f3e1
  paramset:
    ON_TIME: 10
    STATE: true
```
