### DISCUSSION TITLE
switch.turn_on in bestimmten Situationen erzwingen

### DISCUSSION THREAD

**Discussion by gandy92** [SukramJ/aiohomematic#2182] [General]
Ich darf kurz meinen Anwendungsfall schildern:

In meinem Badezimmer steht die Waschmaschine. Wenn dessen Stromverbrauch signalisiert, dass die Waschmaschine gestartet wurde, wird die Raumlüftung (ein Kanal eines lc_sw2pbu_fm) per Automation angeschaltet und nach Beendigung zeitversetzt wieder ausgeschaltet. Das funktioniert soweit ganz gut, wenn der Schalter zum Zeitpunkt des Einschaltens aus war.

Dieser Schalter soll zusätzlich die zeitgesteuerte Lüftung ermöglichen und ist dazu so parametriert, dass der Lüfter bei  kurzem Tastendruck für ein paar Minuten angeht, bei langem Tastendruck ein paar Minuten länger. 

Wurde nun so ein manuelles Lüften ausgelöst und die Waxhmaschine wird gestartet, während der Timer im Schalter noch läuft, so schaltet die Automation den Schalter nicht auch dauerhaft an, weil sein Zustand ja schon "an" ist. So wie ich die hahomematic Dokumentation lese ist das gewollt ("[We try to avoid backend calls if value/state doesn't change](https://github.com/sukramj/custom_homematic?tab=readme-ov-file#sample-for-set_device_value)"), und in den meisten Fällen gibt das auch durchaus Sinn. Sehe ich das richtig, dass diese Optimierung das oben geschilderte Verhalten erklärt?

Nun zu meiner eigentlichen Frage: 

Gibt es eine Möglichkeit, zu erzwingen, dass der Schalter auf dauerhaft-an geschaltet wird, obwohl der Zustand aktuell an ist? Eventuell wie in [Sample for set_device_value](https://github.com/sukramj/custom_homematic?tab=readme-ov-file#sample-for-set_device_value) gezeigt?
```yaml
---
action: homematicip_local.set_device_value
data:
  device_id: abcdefg...
  channel: 1
  parameter: STATE
  value: "true"
  value_type: boolean
```

Oder kann ich dem Service-Call einen Parameter mitgeben, um das Schalten zu erzwingen?
```
action: switch.turn_on
metadata: {}
data: {}
target:
  entity_id: switch.hm_lc_sw2pbu_fm_oeq1228624_ch1
```

Denkbar wäre m.E. auch, den Schalter kurz aus- und wieder einzuschalten. Hierbei habe ich aber (vielleicht unbegründete) Bedenken, dass es zu Situationen kommen könnte, in denen hahomematic den An-Befehl doch wegoptimiert, weil evtl der Aus-Zustand noch nicht zurückgemeldet wurde. Auch würde ich an der Stelle ungern auf ein festes Delay zwischen beiden Befehlen verzichten.

**Comment by SukramJ** [comment]
Wie setzt Du den Timer?

**Reply by gandy92** [reply]
Nicht von Home Assistant aus; das ist im Schalter selbst parametriert, ähnlich wie eine Treppenhauslicht Funktion. 

Edit: Die Parametrieung habe ich damals von FHEM aus vorgenommen, RaspberryMatic erkennt die gesetzten Register aber augenscheinlich nicht. Im Wesentlichen werden für short-press und long-press jeweils folgende Register gesetzt:
```
   ActionType:jmpToTarget 
   OffTime:unused 
   OnTime:0 
   SwJtDlyOff:on 
   SwJtDlyOn:no 
   SwJtOff:dlyOn 
   SwJtOn:no 
   OnDly:0 
   OffDly:<time>
```
Wobei `time` den Wert 900 für short-press (15 Min) und 2700 (45 Min) annimmt. Bei Tastendruck zieht demnach das Relais an und wird nach Ablauf von OffDly abgeschaltet. Erneuter Druck auf den Schalter während der Laufzeit von OffDly setzt den Timer wieder hoch. Abschalten per Taster ist nicht möglich, der Schaltzustand kann aber jederzeit über Funk geändert werden.

**Reply by Baxxy13** [reply]
Also ich hab das mal auf 2 Arten mit einem HM-LC-Sw1-Pl-DN-R1 getestet.

A: Direktverknüpfung mit virt. Taste; Schalter EIN / EINschaltdauer 2Min
B: über ein WebUI-Programm die Einschaltdauer gesetzt und dann EINgeschalten

Am `WORKING` - Datenpunkt (unignore!) sieht man das eine EINschaltdauer aktiv ist.

Ich kann mit...
```yaml
action: homematicip_local.set_device_value
data:
  device_id: 06897cbfc563e6b5c30717e3668ed503
  channel: 1
  parameter: STATE
  value: "true"
  value_type: boolean
```
... oder mit...
```yaml
action: homematicip_local.put_paramset
data:
  device_id: 06897cbfc563e6b5c30717e3668ed503
  channel: 1
  paramset_key: VALUES
  paramset: {"STATE": true}
```
... die laufende EINschaltdauer problemlos "entfernen" (`WORKING` geht auf `false`)

Edit:
mit `switch.turn_on` geht's erwartungsgemäß nicht, eben weil der Switch schon EIN ist.
