### DISCUSSION TITLE
keine Automation über HmIPW-DRI32 möglich, falsche Konfiguration?

### DISCUSSION THREAD

**Discussion by DanielS1290** [SukramJ/aiohomematic#407] [Q&A]
Hallo zusammen!
ich versuche seit einigen Tagen meine RaspberryMatic in HA zu integrieren. Bei Operationen die von HA ausgehen, sprich Aktoren (HmIPW-DRS8) schalten, funktioniert dies bereits. Leider kann ich nicht die Status der Eingangsmodule (HmIPW-DRI32) von der RaspberryMatic "abgreifen" (so mein Verdacht).

Die Eingangsmodule (HmIPW-DRI32) werden zwar erkannt, jedoch sind die Entitäten in der Verlauf-Ansicht permanet als "Aus" gekennzeichnet, obwohl diese benutzt werden und auch durch eine direkte Verknüpfung über die CCU3 UI funktionieren.
Wenn ich in HA eine Automation (siehe unten) erstelle, dann schaltet sich das Licht ein und aus, wenn ich den Button "Aktionen ausführen" betätige, jedoch nicht wenn ich den Wandtaster drücke.

Bein einrichten habe ich mich an [diese Anleitung](https://github.com/danielperna84/custom_homematic) gehalten.

Hier meine Konfigurationen:

/configuration.yaml
```
homematic:
  interfaces:

    Funk:
      host: !secret raspberrymatic_host
      port: 2001
      resolvenames: json
      username: !secret raspberrymatic_username
      password: !secret raspberrymatic_pw
    HMIP:
      host: !secret raspberrymatic_host
      port: 2010
      username: !secret raspberrymatic_username
      password: !secret raspberrymatic_pw
      resolvenames: json
    Wired:
      host: !secret raspberrymatic_host
      port: 2000
      resolvenames: json
      username: !secret raspberrymatic_username
      password: !secret raspberrymatic_pw
    groups:
      host: !secret raspberrymatic_host
      port: 9292
      resolvenames: json
      username: !secret raspberrymatic_username
      password: !secret raspberrymatic_pw
      path: /groups
  hosts:
    ccu3:
      host: !secret raspberrymatic_host
      username: !secret raspberrymatic_username
      password: !secret raspberrymatic_pw
```
/automations.yaml
```
- id: '1649833432995'
  alias: Licht Büro
  description: ''
  trigger:
  - platform: device
    domain: homematicip_local
    device_id: 2462c2f82b90039ce36624d87be9cd5b
    event_type: homematic.keypress
    interface_id: RaspberryMatic-HmIP-RF
    address: 00171A49A01BB9
    type: press_short
    subtype: 18
  condition: []
  action:
  - type: toggle
    device_id: a1b7ab93cb978453bc9d75509ee5cbd5
    entity_id: switch.x_schalt_1_ch14
    domain: switch
  mode: single

```
CCU Firewall
![Unbenannt](https://user-images.githubusercontent.com/102729977/163142385-26040143-d83f-42d7-af39-f769c5f1fce4.JPG)

XML-RPC
![Unbenannt3](https://user-images.githubusercontent.com/102729977/163142632-89565772-7d46-409c-9b48-a25ab72817f6.JPG)

Fällt evtl. jemandem eine fehlerhafte Konfiguration auf?
Danke für Eure Hilfe!
