### DISCUSSION TITLE
BUTTON_LOCK not changing on HM-CC-RT-DN device - How to find the correct parameter name?

### DISCUSSION THREAD

**Discussion by Rainerlan** [SukramJ/aiohomematic#471] [Q&A]
Ich möchte einen Template sensor erstellen, um den "lock-button" meines HM-CC-RT-DN Heizkörperthermostats zu ändern.
Leider ist der Lock-button nicht automatisch als entity angelegt.
Eine Automatisierung tuts aber auch :)

Folgendes habe ich (erfolglos) ausprobiert:
```
service: homematicip_local.set_device_value
data:
  device_id: homematicip_local.neq1411051
  parameter: BUTTON_LOCK
  value: 'true'
  value_type: boolean
  channel: 0
```
Ich nehme an, dass die *device_id* falsch ist.
Kann mir bitte jemand erklären, wie ich die device_id herausfinden kann?

**Comment by Rainerlan** [comment]
Habe mittlerweile die device_id gefunden: 
In "Entwicklungswerkzeuge"->"Dienste"->"homematicip_local.set_device_value" das Gerät auswählen und auf dem YAML modus wechseln.
D.h .die Device ID ist jetzt sicher korrekt

Leider ändert sich der BUTTON_LOCK-status nicht am Gerät.

Wie kann ich den korrekten parameter-name herausfinden?

```
service: homematicip_local.set_device_value
data:
  device_id: 3fda7b18f76f84e02b7b4c430130f2c8
  parameter: BUTTON_LOCK
  value: 'true'
  value_type: boolean
  channel: 0
```

Der Parameter scheint korrekt zu sein:
[https://community.symcon.de/t/homematic-hm-cc-rt-dn-globale-bediensperre-ueber-skript-de-aktivieren/37923/5](url)

Aber auch das funktioniert nicht:
```
service: homematicip_local.put_paramset
data:
  device_id: 3fda7b18f76f84e02b7b4c430130f2c8
  paramset_key: MASTER
  paramset: 
    BUTTON_LOCK: true
```

**Reply by SukramJ** [reply]
Ich würde an deiner Stelle mal mit dem [Homematic Manager ](https://github.com/hobbyquaker/homematic-manager/releases) anfangen, und schauen wie man damit die Bediensperre setzten kann.

**Comment by Baxxy13** [comment]
Der Parameter ist schon korrekt.
Das Problem scheint zu sein das `homematicip_local.put_paramset` zwingend die Übergabe eines Kanals voraussetzt.
Bei den klassischen Geräten liegen aber die MASTER-PARAMETER direkt im Gerät und nicht in den Kanälen.
![MASTER_PARAMSET_HM_Kassik](https://user-images.githubusercontent.com/54898249/171118829-df610771-a7a1-4ff0-a1cc-ea3c030624dc.JPG)

**Comment by Rainerlan** [comment]
Kann ich denn irgendwie feststellen, was die Home Assistant Komponente wirklich über die XML-RPC Verbindung ans RaspberryMatic Addon schickt? In irgendeinem log vielleicht?

Handelt es sich hier vielleicht noch ein prinzipielles Problem der Home Assistant Komponente?

Ich hatte alle Kanäle bereits durchprobiert (Und ich dachte bisher Kanal 0 eines Geräts entspricht dem 'MASTER' - Paramesets kenne ich aus FHEM bisher nicht;) - dort wird der BtnLock einfach im "Hauptgerät" angezeigt)

D.h. Unter Angabe eines Kanals funktioniert das setzten des Button-Locks ebenfalls nicht...:
```
service: homematicip_local.put_paramset
data:
  device_id: 3fda7b18f76f84e02b7b4c430130f2c8
  paramset_key: MASTER
  channel: 0
  paramset:
    BUTTON_LOCK: 'true'
```

**Reply by SukramJ** [reply]
Nein, das geht nicht.

- Benutze den Homematic Manager.
- Ändere den Wert
- Beim Senden wird das verwendete ParamSet angezeigt.
- Wenn es funktioniert hat, dann poste das ParamSet hier

**Comment by Baxxy13** [comment]
Wie geschrieben liegen die MASTER-Parameter bei HM direkt im Gerät und nicht in irgend einem Kanal.
Ergo darf man mit `homematicip_local.put_paramset ` auch keinen Kanal übergeben.

Das lässt die Funktion aber nicht zu. Ohne "channel:" lässt sie sich erst gar nicht ausführen.
```
service: homematicip_local.put_paramset
data:
  device_id: 434b492d40becbab331cd36bd2cfc975
  paramset_key: MASTER
  paramset:
    BUTTON_LOCK: true
```
Mit "leerem "channel:" ...
```
service: homematicip_local.put_paramset
data:
  device_id: 434b492d40becbab331cd36bd2cfc975
  channel:
  paramset_key: MASTER
  paramset:
    BUTTON_LOCK: true
```
... wirft die Funktion Fehler:
```
2022-05-31 19:45:55 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: expected int for dictionary value @ data['channel']
2022-05-31 19:45:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140290555188992] Error handling message: expected int for dictionary value @ data['channel']. Got None (invalid_format)
```

Mit dem Homematic-Manager sieht das so aus:
```json
putParamset [
  "QEQ1958978",
  "MASTER",
  {
    "BUTTON_LOCK": false
  }
]
```

**Reply by SukramJ** [reply]
Danke @Baxxy13, das ist sehr hilfreich.

**Reply by SukramJ** [reply]
Bitte mit der 1.7.1 testen.

**Reply by Rainerlan** [reply]
Leider funktionert das setzen des BUTTON_LOCK bei mir noch nicht - die Fehlermeldung bei fehlendem "channel" ist aber verschwunden.

```
service: homematicip_local.put_paramset
data:
  device_id: 3fda7b18f76f84e02b7b4c430130f2c8
  paramset_key: MASTER
  paramset:
    BUTTON_LOCK: 'true'
```

Auf die Gefahr hin ein völlig dumme & off-topic Frage zu stellen ohne zuvor die Forum-Suche bemüht zu haben:
Damit der Homematic Manager (auf meinem Windows PC) eine Verbindung zum RaspberryMatic in hassio bekommt - muss ich außer der IP des Raspi (auf dem hassio läuft) noch was anderes eingeben? Ich habe es mit und ohne "Use Auth" versucht.

Note: In RaspberryMatic sind alle Ports freigegeben - leider findet der Homematic Manager keine Gräte, und er zeit nur "Ladevorgang..." an
