### DISCUSSION TITLE
WARNING '' Value of sysvar '' exceedes maximum allowed length of 255 chars. - Warnmeldungen ausblenden?

### DISCUSSION THREAD

**Discussion by Baxxy13** [SukramJ/aiohomematic#476] [Q&A] [answered]
Weiß nicht seit wann genau, aber aktuell wird mein Log alle 30s mit ca. 10 solcher Einträge (für diverse SysVars) gefüllt.
`2022-05-31 22:23:18 WARNING (MainThread) [hahomematic.hub] Value of sysvar AskSinAnalyzerDevList exceedes maximum allowed length of 255 chars. Value will be limited to 255 chars.`
Woher es kommt ist klar, meine Text-SysVars sind einfach zu gut gefüllt.
In der `configuration.yaml` habe ich aktuell folgende Logger-Einstellungen drin:
```
logger:
  default: warning
  logs:
    hahomematic: info
    homeassistant.components.hahm: info
```
Ist das noch korrekt? 

Da ich viel ausprobiere würde ich das Logging gerne "feinfühlig" belassen.
Gibt es da vielleicht eine Filteroption um obige Meldungen auszublenden?

Die Systemvariablen sind laut Status auch alle deaktiviert, brauche ich aktuell auch nicht.

Jegliche Tipps sind willkommen!

Grüße, Baxxy

**Comment by SukramJ** [comment]
Du kannst mal deinen Logger erweitern:

```
logger:
  default: warning
  logs:
    hahomematic: info
    hahomematic.hub: error
    homeassistant.components.hahm: info
```

Ich möchte das `log level` eigentlich auf `warning` belassen, da ansonsten eine längere Fehlmeldung der HA State machine im log erscheinen würde.
Ich schau mal, ob man die Meldung auf aktive Entitäten reduzieren kann.

Was hast Du eigentlich in den Sysvars?
