### DISCUSSION TITLE
Wie Rampe beim ein/ausschalten eines Dimmers aktivieren?

### DISCUSSION THREAD

**Discussion by stuckis6er** [SukramJ/aiohomematic#508] [Q&A]
Hallo,
ich versuche einen HmIP-PDT Dimmer langsam hoch/runter zu dimmen. Das wollte ich mit diesem Code erreichen.

```
service: homematicip_local.set_device_value
data:
  channel: 3
  device_id: 188b92842c7b67f2f95234dcb0076383
  parameter: RAMP_TIME
  value: '10'
  value_type: int
```

Allerdings ändert sich beim nächsten Schaltvorgang mit light.turn_on leider nichts. Gibt es da eine Lösung?

Gruß Ralf
