### DISCUSSION TITLE
Steuerung von Jalousien

### DISCUSSION THREAD

**Discussion by riesi77** [SukramJ/aiohomematic#560] [Q&A]
Hallo,

gibt es soetwas wie best practices um eine Steuerung eines HMIP Jalousieaktors (spezifisch: HmIP-BROLL) zu realisieren? Soweit ich herausgefunden habe, kann ich direkt über die Entity (in Home Assistant natürlich) gehen, oder über das Cover Service.
Im Endeffekt möchte ich nur unabhängig von der Ausgangsposition eine Behanghöhe + Öffnungswinkel definieren (Über ein Skript). Homematic bietet das ja in einer Aktion an - Home Assistant hat dafür 2 verschiedene Aktionen. Und ich bin mir nicht sicher, welche zuerst auszuführen ist - und ob zwischen den Aktionen noch etwas zu beachten ist. Erreichen möchte ich ein Skript "Halboffen", das das Raffstore runterfährt (wenn es das nicht ist) und dann die Öffnung auf 70% stellt.

Danke.

**Comment by ThomDietrich** [comment]
Hallo,
ich mag einen Teil deiner Frage falsch verstanden haben, ansonsten bekommst du mit reinen Home Assistant Fragen in der Community schnelle Unterstützung.

So steuere ich meine Rollos (zwei Beispiele):

```yaml
  - id: "162637674703"
    alias: Regel Rollos Morgens öffnen
    trigger:
      - platform: time
        at: "09:00:00"
    action:
      - service: cover.set_cover_position
        entity_id:
          - cover.kueche
          - cover.schlafzimmer
          - cover.bad
        data:
          position: 100

  - id: "162637674713"
    alias: Regel Rollo Bad bei offenem Fenster
    trigger:
      - platform: state
        entity_id: binary_sensor.bad_fenster
        to: "on"
    condition:
      - condition: numeric_state
        entity_id: cover.bad
        attribute: current_position
        below: 20
    action:
      - service: cover.set_cover_position
        entity_id:
          - cover.bad
        data:
          position: 35

```

**Reply by riesi77** [reply]
Danke Thom,
danke. Ich denke prinzipiell  hat du die Frage richtig verstanden - nur habe ich Raffstores, keine Rollläden. Und damit neben der Position auch noch den Öffnungswinkel (cover.tilt_position). Und das funktioniert bei mir nicht zuverlässig.

**Reply by ThomDietrich** [reply]
Ich würde erwarten dass mindestens das folgende funktioniert. Probiere die beiden Dienste auch mal getrennt. Sollte es nicht funktionieren könnte es sich um einen Fehler hier im Projekt handeln.

```yaml
    action:
      - service: cover.set_cover_position
        entity_id: cover.bad
        data:
          position: 35
      - service: cover.set_cover_tilt_position
        entity_id: cover.bad
        data:
          tilt_position: 50
```

**Reply by SukramJ** [reply]
Nach dem ersten Serviceaufruf muss eine Verzögerung eingebaut werden, da ansonsten der zweite Serviceaufruf den Ersten abbricht.

**Reply by ThomDietrich** [reply]
Das hatte ich auch vermutet, daher der Rat die Befehle einzeln aufzurufen. Teste mal das:

```yaml
    action:
      - service: cover.set_cover_position
        entity_id: cover.bad
        data:
          position: 35
      - wait_template: "{{ is_state_attr('cover.bad', 'current_position', 35) }}"
      - service: cover.set_cover_tilt_position
        entity_id: cover.bad
        data:
          tilt_position: 50
```

**Reply by riesi77** [reply]
Danke, das hört sich gut an und werde ich mal versuchen.
Wenn ich nun 2 Raffstores (Sagen wir: Bad Süd und Bad Ost) gemeinsam über ein Skript steuern wollte. Wie formuliere ich da dann das wait template? Gibt es da eine Verknüpfung, sodass beide auf "Position 35" sein müssen?

**Reply by ThomDietrich** [reply]
Da musst du definitiv mal etwas experimentieren aber das folgende könnte grob die Lösung sein:

```yaml
    action:
      - service: cover.set_cover_position
        entity_id:
          - cover.bad_sued
          - cover.bad_ost
        data:
          position: 35
      - wait_template: "{{ is_state_attr('cover.bad_sued', 'current_position', 35) and is_state_attr('cover.bad_ost', 'current_position', 35) }}"
      - service: cover.set_cover_tilt_position
        entity_id:
          - cover.bad_sued
          - cover.bad_ost
        data:
          tilt_position: 50
```
