### DISCUSSION TITLE
Raffstore / Jalousie in Szene steuern

### DISCUSSION THREAD

**Discussion by eikowagenknecht** [SukramJ/aiohomematic#628] [Q&A]
Hallo zusammen,

ich versuche gerade, meine Jalousieaktoren per Szene so einzustellen, dass sie auf x% mit Öffnungswinkel y landen. Dazu habe ich folgende Konfig:

```
- name: Schatten im Wohnzimmer
  entities:
    cover.eg_wohnen_raffstore_terrasse:
      current_position: 40
      current_tilt_position: 0
      state: open
    cover.eg_wohnen_raffstore_tuer:
      current_position: 35
      current_tilt_position: 0
      state: open
```

Wenn ich das nun ausführe, wird bei einem der Raffstore entweder Position oder Tilt eingestellt. Komplett zufällig, bei welchem. Wenn ich das nun oft genug ausführe habe ich am Ende den gewünschten Zustand. Wäre aber natürlich schön, wenn es nur einen Anlauf bräuchte.

Meine Vermutung ist, dass Home Assistant hier einfach 4 Befehle an Homematic sendet und davon nur einer ausgeführt wird. Kann das sein? Lässt sich das irgendwie korrigieren oder muss ich eine Lösung ohne Szenen suchen (wie sie hier untere anderem schon für Automatisierungen diskutiert wurde in einem anderen Thread)?

Viele Grüße

Eiko

**Comment by SukramJ** [comment]
Ich habe keine Raffstores / Jalousien, daher wurde die Funktionalität zusammen mit Benutzern umgesetzt.

Ich gehe mal davon aus das Du BidCos Geräte verwendest.

Es gibt zwei Services für Raffstores / Jalousien die, wie ich denke,  hier relevant sind:
- `cover.set_position`
- `cover.set_tilt_position`

 ```
cover.eg_wohnen_raffstore_terrasse:
      current_position: 40
      current_tilt_position: 0
      state: open
```

Die Ausführung sähe demnach so aus:

1. cover.set_position(40)
2. cover.set_tilt_position(0)

Ich könnte mir vorstellen das Befehl 2 Befehl 1 abbricht.
Wenn dem so ist, dann ist die Umsetzung als Szene für Homematic ungeeignet.

Eine Umsetzung wie in #560 beschrieben scheint hier sinnvoller zu sein.
