### DISCUSSION TITLE
Add virtual channels of actuators

### DISCUSSION THREAD

**Discussion by ce3a** [SukramJ/aiohomematic#694] [Ideas]
**Is your feature request related to a problem? Please describe.**
Shutter close and open requests from Home Assistant shall go to multiple virtual channels of the shutter actuator. 
The virtual channels (5 and 6) of the HmIP-BROLL shutter actuator are not available in Home Assistant.

**Describe the solution you'd like**
I would like the virtual channels (5 and 6) of the HmIP-BROLL shutter actuator to be available in Home Assistant.

**Comment by SukramJ** [comment]
Within this integration all shutter/blinds are controlled with the first actor (channel 4), but these actor channels do not report the current level correct.
This has been an issue with the old integration, witch was not solvable (by design) and a reason for creating the new integration.
So for cover entities we control the device with the first actor (channel 4) but use the level from the status channel (3) to get the correct position.
That also makes the usage channel 5 +6 as control channel for cover entities useless, because that would either lead to cover entities with the wrong status(use level from own channel), or to an equivalent to the existing cover entity (use level from status channel).

What is your use case why channels 5+6 are relevant?

**Reply by ce3a** [reply]
I am using channels 4 and 5. These channels are or-ed in the CCU, meaning the higher level wins. With that I can configure the following without any scripts:

At 9:00 set the shutter position to 50% but only if the position is below 50%. In other words, if I opened the shutters fully before 9:00, I don't want them to go back to 50% at 9:00. 

This is done by setting only channel 5 to 50% at 9:00. Other triggers are setting both channels. HA should set both channels as well. Setting channel 4 only is not enough, the shutter will not close, because a higher level is requested via channel 5 and the higher level wins.

**Reply by SukramJ** [reply]
If you want to control channel 5 in the script/automation, your best option is to use the services `homematicip_local.set_device_value` or `homematicip_local.set_device_value_raw` and set the parameter `LEVEL`. Values are between `0.0`(closed) and `1.01`(open).
As written above reading LEVEL on these channels is "strange", and should not be necessary as you described above.

**Reply by ce3a** [reply]
I think I don't need to read from these channels. The actual position is reported on channel 3, not 4, 5 or 6.

**Reply by SukramJ** [reply]
Correct

**Reply by ce3a** [reply]
Can I make channel 5 available as an entity?

**Reply by SukramJ** [reply]
Option 1: You can use a cover template with. The service calls i mentioned above.
Option 2: Use [unignore](https://github.com/danielperna84/custom_homematic#unignore-device-parameters) and add LEVEL to the file, that would create a number entities for all devices with LEVEL parameter.

**Reply by ce3a** [reply]
Thanks a lot @SukramJ !

I am able to open and close the cover by writing a value between `0.0` and `100.0` to the channel 5 entity. 

But how do I STOP it?

**Reply by SukramJ** [reply]
Use the Channel 4 Cover entity?

**Reply by SukramJ** [reply]
Or Service cover.stop.

**Reply by SukramJ** [reply]
Or set parameter STOP on channel 5 to True

**Reply by ce3a** [reply]
Thanks again @SukramJ. I finally got it working like that:

```yaml
cover:
  - platform: template
    covers:
      group_cover_schlafzimmer:
        device_class: shutter
        friendly_name: "Rolladen Schlafzimmer"
        value_template: >-
          {{ states('cover.rolladen_schlafzimmer') }}
        position_template: >-
          {{ states('sensor.rolladen_schlafzimmer_rolladenschalter_schlafzimmer_level_ch3') }}
        availability_template: >-
          {{ states('cover.rolladen_schlafzimmer') != 'unavailable' }}
        open_cover:
          service: script.cover_group_open
          data:
            entity_id: cover.rolladen_schlafzimmer
        close_cover:
          service: script.cover_group_close
          data:
            entity_id: cover.rolladen_schlafzimmer
        stop_cover:
          service: script.cover_group_stop
          data:
            entity_id: cover.rolladen_schlafzimmer
        set_cover_position:
          service: script.cover_group_set_position
          data:
            entity_id: cover.rolladen_schlafzimmer
            position: "{{position}}"

script:
  cover_group_open:
    sequence:
      - service: cover.open_cover
        target:
          entity_id:
            - "{{entity_id}}"
      - service: homematicip_local.set_device_value
        data:
          device_id: "{{ device_id(entity_id) }}"
          channel: 5
          parameter: LEVEL
          value: "1.0"
          value_type: double
  cover_group_close:
    sequence:
      - service: cover.close_cover
        target:
          entity_id:
            - "{{entity_id}}"
      - service: homematicip_local.set_device_value
        data:
          device_id: "{{ device_id(entity_id) }}"
          channel: 5
          parameter: LEVEL
          value: "0.0"
          value_type: double
  cover_group_stop:
    sequence:
      - service: cover.stop_cover
        target:
          entity_id:
            - "{{entity_id}}"
      - service: homematicip_local.set_device_value
        data:
          device_id: "{{ device_id(entity_id) }}"
          channel: 5
          parameter: STOP
          value: "True"
          value_type: boolean
  cover_group_set_position:
    sequence:
      - service: cover.set_cover_position
        target:
          entity_id:
            - "{{entity_id}}"
        data:
          position: "{{position}}"
      - service: homematicip_local.set_device_value
        data:
          device_id: "{{ device_id(entity_id) }}"
          channel: 5
          parameter: LEVEL
          value: "{{ position | float / 100.0 }}"
          value_type: double

```
