### DISCUSSION TITLE
CCU not found properly?

### DISCUSSION THREAD

**Discussion by hvg1** [SukramJ/aiohomematic#707] [Q&A]
Up until a couple of days ago I was using HomeAssistant (2022.11.2) with the RaspberryMatic CCU Addon (3.65.11.20221005) and the HomeMatic integration via the _configuration.yaml_. Since I found the integration provided over HACS I tried to activate it and switch over, but after I add the integration and configure it, it only shows one service and no entities - also the service is shown as "CU by eQ-3" not as I've seen on screenshots as "CCU by eQ-3"?!
The RaspberryMatic Addon is working properly, also if I switch back to the integration via the _configuration.yaml_ it's still working as intended. Am I missing something or doing something wrong?
What is irritating me is that the log says `Unable to open session: Cannot connect to host de838cd8-raspberrymatic:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')]` along with those errors:
```
_do_post failed: ClientConnectorError
_do_login failed: Unable to open session: Cannot connect to host de838cd8-raspberrymatic:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')]
_post_script failed: Error while logging in via JSON-RPC.
_post failed: Error while logging in via JSON-RPC.
```
After that there are only warnings in the log:
```
_create_clients failed: Interface: HmIP-RF is not available for backend.
_create_clients failed: Interface: BidCos-RF is not available for backend.
_create_clients failed: Interface: VirtualDevices is not available for backend
```

What I was using in the _configuration.yaml_:
```
homematic:
  interfaces:
    rf:
      host: de838cd8-raspberrymatic
      port: 2001
      resolvenames: json
      username: ...
      password: ...
    wired:
      host: de838cd8-raspberrymatic
      port: 2000
      resolvenames: json
      username: ...
      password: ...
    hmip:
      host: de838cd8-raspberrymatic
      port: 2010
      resolvenames: json
      username: ...
      password: ...
    groups:
      host: de838cd8-raspberrymatic
      port: 9292
      resolvenames: json
      username: ...
      password: ...
      path: /groups
  hosts:
    raspberrymatic:
      host: de838cd8-raspberrymatic
      username: ...
      password: ...
```

The diagnostics from the Homematic(IP) Local integration:
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.11.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Vienna",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.10.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "solax_modbus": {
      "version": "0.7.0.4",
      "requirements": [
        "pymodbus>=2.5.3",
        "pymodbus<=3.0.1"
      ]
    },
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "homematicip_local": {
      "version": "1.21.2",
      "requirements": [
        "hahomematic==2022.11.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2022.11.1"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.21.2",
    "integration_type": "hub",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "f9958621bbe7200baeaad2224efef253",
      "version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "de838cd8-raspberrymatic",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          },
          "VirtualDevices": {
            "port": 9292,
            "path": "/groups"
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "unknown",
      "disabled_by": null
    },
    "platform_stats": {},
    "devices": []
  }
}
```
I hope I provided all necessary infos :wink:
I'm running this on a RPi 4 with a RPI-RF-MOD by the way, with both HomeMatic and HomeMatic IP devices.
