### DISCUSSION TITLE
Ability to change preset while in non-auto mode for climate devices

### DISCUSSION THREAD

**Discussion by hcrohland** [SukramJ/aiohomematic#718] [Ideas]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
I have an automation which switches the preset for a climate devices when somebody enters or leaves the house.
Now, when the climate device is in manual mode, this switching is not available. Due to that, the next time the device is switched to auto mode, it often has the wrong state. 

**Describe the solution you'd like**
I'd like to switch the preset in any mode, not only in "auto" mode. This is possible in the Raspberrymatic UI

**Describe alternatives you've considered**
I might enhance the automation to temporarily switch to "auto". 

**Additional context*
![Bildschirmfoto 2022-11-28 um 19 53 40](https://user-images.githubusercontent.com/18126119/204357684-2b0a098b-b04c-403b-ac67-b65610f62e05.png)

**Comment by hcrohland** [comment]
Okay, after going through the source code, I found another workaround:

```
service: homematicip_local.set_device_value
data:
  device_id: ****
  parameter: active_profile
  value_type: int
  channel: 1
  value: "2"
```
