### DISCUSSION TITLE
HmIP-Broll - Auto/Manu Modus auslesen

### DISCUSSION THREAD

**Discussion by smonsi** [SukramJ/aiohomematic#779] [Q&A] [answered]
Hallo Leute,
erst einmal ein großes Dankeschön für die tolle HA HM Integration!

Ich würde gerne die Eigenschaft Automatikmodus bzw. Manueller Modus des HmIP-Broll auslesen um diese dann über eine Umschalter darzustellen und zu verändern.

Mittels set_device_value Service kann ich den Wert verändern, hier z.B. 
```
service: homematicip_local.set_device_value
data:
  device_id: ec9b943bc2673d8a44c7334523912cdd
  channel: 7
  parameter: COMBINED_PARAMETER
  value: WPTCLS=1,WPTCL=0
```
Allerdings ist mir nicht klar, wie ich den aktuellen Zustand aus HM auslesen kann. 
Die Lösung über unignore die entsprechenden Parameter vom Channel 7 - BLIND_WEEK_PROFILE einzubinden liefert leider keine Entities für folgende Parameter:
WEEK_PROGRAM_CHANNEL_LOCKS
WEEK_PROGRAM_TARGET_CHANNEL_LOCK
WEEK_PROGRAM_TARGET_CHANNEL_LOCKS
COMBINED_PARAMETER

Gibt es andere Möglichkeiten?

Schöne Grüße
Horst
