### DISCUSSION TITLE
Gibt es eine Möglichkeit beim HM-Dis-EP-WM55 Display Taster die Tasten durch HA zu beschriften?

### DISCUSSION THREAD

**Discussion by kwithus** [SukramJ/aiohomematic#876] [Q&A] [answered]
Moin
Ich habe einen HM-Dis-EP-WM55 Display Taster, beim dem in Homematic die Tasten in den Einstellungen beschriften werden können, bzw. Die Beschriftung des Displays eben in den Einstellungen definiert wird.
Gibt es eine Möglichkeit, dies in HA zu erledigen? Dann könnte man eventuell die Tasten auch dynamisch beschriften, d.h. Die Beschriftungstexte durch eine Automatisierung oder ein Skript ändern lassen.

**Comment by Baxxy13** [comment, marked as answer]
> Gibt es eine Möglichkeit, dies in HA zu erledigen?

Ja. 
```
service: homematicip_local.put_paramset
data:
  device_id: 47fe0396b09cbb5d6624265db92f14df
  channel: 2
  paramset_key: MASTER
  paramset:
    TEXTLINE_1: 'Nice :-)'
```

Beschreibt die obere Taste also die erste Zeile (Zeile 1)

Zeile 1 = channel: 2 / TEXTLINE_1
Zeile 2 = channel: 2 / TEXTLINE_2
Zeile 4 = channel: 1 / TEXTLINE_1
Zeile 5 = channel: 1 / TEXTLINE_2

Das Beschreiben geht ordentlich auf den Duty-Cycle der Zentrale, ich würde da "vorsichtig" rangehen.

**Reply by kwithus** [reply]
Danke,
Jetzt geht es, zunächst tat sich nichts, das lag aber an der CCU zu HA Verbindung, die hatte sich aufgehängt.

**Reply by kwithus** [reply]
Weißt Du auch, wie ich die anderen Zeilen nutzen kann?
Es gibt ja die Möglichkeit in den Geräteeinstellungen in channel 4 -
Jeweils 2 Textblöcke zu definieren. Ich habe versucht, diese Channel aus HA heraus analog zu bespielen, geht aber nicht.
Außerdem kann man dann in der WebUI in Programmen die Zeilen 2-4 entweder mit diesen Textblöcken belegen oder man kann eigenen Text eingeben.
Dazu dann noch jeweils Icons vergeben und definieren, ob die Lampe blinken oder ein Ton ertönen soll und wie oft.
Geht das alles auch „irgendwie“ von HA aus?
Oder muss ich dafür dann auf Progs in der WebUI zurückgreifen und die von HA aus auslösen?
Danke für die Hilfe

**Reply by Baxxy13** [reply]
Probier das mal... ;-)

```
service: homematicip_local.set_device_value
data:
  device_id: 47fe0396b09cbb5d6624265db92f14df
  channel: 3
  parameter: SUBMIT
  value_type: string
  value: '0x02,0x0A,0x12,0x42,0x61,0x78,0x78,0x79,0x0A,0x12,0x73,0x61,0x67,0x74,0x2e,0x2e,0x2e,0x0A,0x12,0x50,0x69,0x65,0x70,0x20,0x70,0x69,0x65,0x70,0x0A,0x0A,0x14,0xC5,0x1C,0xD1,0x1D,0xE0,0x16,0xF1,0x03'

```
