### DISCUSSION TITLE
In the HA card custom:simple-thermostat is see week_program_1

### DISCUSSION THREAD

**Discussion by Mika255** [SukramJ/aiohomematic#921] [Q&A] [answered]
Hi, since the last update, i'm seeing "week_program_xy" in the UI of the simple-thermostat.
Any way to map this to a meaningful name? 

I've tried to delete the cache and to use another browser... but still no luck.
I've also tried to switch to UK English and German.

<img width="433" alt="Screenshot 2023-02-04 at 23 37 50" src="https://user-images.githubusercontent.com/67970450/216792394-53ef4ff5-a5ba-48aa-9b43-123f75bbd656.png">

```
type: custom:simple-thermostat
entity: climate.bz_heizungsgruppe
layout:
  mode:
    names: true
    icons: true
    headings: false
control:
  preset:
    away: true
    none: false
    boost: true
    Profile 1: true
    Profile 2: true
    Profile 3: false
  hvac: true
header:
  name: Badezimmer
sensors:
  - entity: binary_sensor.bz_fensterkontakt_state
    name: Window

```

**Comment by SukramJ** [comment]
Option 1: Use the default cards of HA.
Option 2: Ask the maintainer of your card to use the translated/localized values.

**Comment by Mika255** [comment, marked as answer]
Thanks @SukramJ . I will contact the maintainer of this thermostat card. And, I have found a third solution after some trial&error. 
Maybe this will help other struggling with the same issue:

Excerpt:
```
    week_program_1:
        name: Profil 1
    week_program_2:
      name: Profil 2
```

<img width="398" alt="Screenshot 2023-02-04 at 23 51 10" src="https://user-images.githubusercontent.com/67970450/216792802-23eded67-1852-4994-8777-62213e937def.png">


Full card:
```
type: custom:simple-thermostat
entity: climate.bz_heizungsgruppe
layout:
  mode:
    names: true
    icons: true
    headings: false
control:
  preset:
    away: false
    none: false
    boost: 
      name: Boost
    week_program_1:
        name: Profil 1
    week_program_2:
      name: Profil 2
    week_program_3:
      name: Profil 3
  hvac: true
header:
  name: Badezimmer
sensors:
  - entity: binary_sensor.bz_fensterkontakt_state
    name: Window

```
