### DISCUSSION TITLE
HmIP-SWSD - Use as siren

### DISCUSSION THREAD

**Discussion by AlphaZuluNRW** [SukramJ/aiohomematic#955] [Q&A] [answered]
I'm using two HmIP-SWSD. In the CCU3 I wrote a script, that started an alarm on the HmIP-SWSD, when one of the HM-Sec-SD-2 detected smoke. I wanted to do the same now in Home Assistant, but I can't start any actions there using the HmIP-SWSD.

Is this a bug in the integration that treats the HmIP-SWSD like a normal smoke detector?

![image](https://user-images.githubusercontent.com/109111462/218312493-5e915e2c-3b21-482c-895c-cad51ad9f636.png)

**Comment by SukramJ** [comment, marked as answer]
This feature was deliberately not implemented for the known reasons.
But if you want to take over the testing, one can perhaps also think about taking it over into the integration.

Looks like the relevant parameter is SMOKE_DETECTOR_COMMAND on Channel 1 with the following value list:
```
0 = "RESERVED_ALARM_OFF",
1 = "INTRUSION_ALARM_OFF",
2 = "INTRUSION_ALARM",
3 = "SMOKE_TEST",
4 = "COMMUNICATION_TEST",
5 = "COMMUNICATION_TEST_REPEATED"
```

To activate the Intrusion alarm you could try to call a service like:

```
service: homematicip_local.set_device_value
data:
  device_address: "1234"
  channel: 1
  parameter: SMOKE_DETECTOR_COMMAND
  value: 2
  value_type: int
  
```

To deactivate the alarm you could try the value `1`.

Please report back if it works.
